### ISSUE TITLE
Legacy nvim mouse messages support

### ISSUE THREAD

**Issue by nree** [yatli/fvim#101]
Mouse doesn't seem to work on Win 10 -> wsl1 (neovim 0.3.8) 
Not sure if I need to do anything special besides 'set mouse'.

So I run same config but do it in Win10 no wsl, and using neovim 0.4.3 and mouse works.

**Comment by yatli** [comment]
I removed the support for legacy mouse events a while ago.

Should add it back.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yatli** [comment]
Let's close it for now as the neovim versions are moving forward and new events are being added.
