### ISSUE TITLE
Win10 -> WSL1 coc.nvim suggestions don't show

### ISSUE THREAD

**Issue by nree** [yatli/fvim#102]
Win10 -> wsl1 -> neovim 0.3.8

Coc.nvim doesn't show suggestions (I _think_ it use to, but not sure). However the plugin works because I can cycle ctrl+n\p suggestions or tab to select. I just cannot see the pop up.

So if I run neovim 0.3.8 locally in terminal I can see it fine.

And then if I run fvim + neovim 0.4.3 without wsl, it works fine there too. 

Same vim setup for everything.

**Comment by yatli** [comment]
Similar to https://github.com/yatli/fvim/issues/101 .
Upgrade to `v0.4`, or set up ginit.vim with:

```
    FVimUIPopupMenu v:false
```

and try again?

Thanks.

**Comment by nree** [comment]
Yes works after `FVimUIPopupMenu v:false`
