### ISSUE TITLE
fvim can not show some airline symbols, but nvim-qt can with the same font.

### ISSUE THREAD

**Issue by jdhao** [yatli/fvim#107]
I am using the font Hack for both fvim and nvim-qt. But nvim-qt can show the branch and percent symbol used by airline, while fvim will render these two symbols as hollow box. See the image below for an example (left image is fvim and right image is nvim-qt)

![image](https://user-images.githubusercontent.com/16662357/71502820-39a83680-28ad-11ea-8cb4-68d4f34bf45d.png)

**Comment by Zardoz89** [comment]
Same with Nerd fonts

![imagen](https://user-images.githubusercontent.com/888483/73741136-e77af080-4749-11ea-84bb-5803e6628fd1.png)

**Comment by yatli** [comment]
Should be a fallback calculation error.

**Comment by yatli** [comment]
Tracking: #103
