### ISSUE TITLE
Does not work well with the default colorscheme/cursor setting

### ISSUE THREAD

**Issue by codehz** [yatli/fvim#11]
version: 0.1.125
![image](https://user-images.githubusercontent.com/13158903/58064902-78a73880-7bb6-11e9-8d01-f2378c96c21c.png)
and there is CJK character rendering problem...
![image](https://user-images.githubusercontent.com/13158903/58064995-cb80f000-7bb6-11e9-9bfd-dd8231be3df0.png)
NOTE: the text color is same as background (white)..

**Comment by codehz** [comment]
OK, the CJK render is ok when I set guifont in init.vim
![image](https://user-images.githubusercontent.com/13158903/58065342-f6b80f00-7bb7-11e9-91a9-8a27def84685.png)
but the main text color is still white

**Comment by codehz** [comment]
![image](https://user-images.githubusercontent.com/13158903/58065427-43034f00-7bb8-11e9-87f8-c55b7113bf83.png)
the font color in the status bar

**Comment by yatli** [comment]
logs?
colorscheme?
anything special in your config?

**Comment by codehz** [comment]
the first screenshot is PaperColor
and then, I rename the .config/nvim to another folder in order to using empty config..
now it is copied from readme
```vim
if exists('g:fvim_loaded')
    " good old 'set guifont' compatibility
    set guifont=Sarasa\ Term\ SC:h16
    set termguicolors=true
    " Ctrl-ScrollWheel for zooming in/out
    nnoremap <silent> <C-ScrollWheelUp> :set guifont=+<CR>
    nnoremap <silent> <C-ScrollWheelDown> :set guifont=-<CR>
    nnoremap <A-CR> :call rpcnotify(1, 'ToggleFullScreen', 1)<CR>
endif
```

**Comment by yatli** [comment]
Actually, `g:fvim_loaded` only works in `ginit.vim`. I should've put that in the readme :)

**Comment by yatli** [comment]
Investigating. I'll try empty config.

**Comment by yatli** [comment]
Can confirm the problem. Looks like the default colors are not playing well.

**Comment by yatli** [comment]
@codehz please try latest master. reopen if it's not working for you.
