### ISSUE TITLE
FocusLost event is not detected

### ISSUE THREAD

**Issue by jdhao** [yatli/fvim#111]
Using Fvim on Windows 10 (version 1803). I have set up in my Neovim config to turn off relative line number when the window focus is lost. For fvim, when the focus is lost, the relative line number is not turned off.

Nvim-qt works fine on this.

**Comment by yatli** [comment]
Never realized that hook exists!
Thanks, I'll implement this one.

**Comment by jdhao** [comment]
It does exist and I am currently using [this vim plugin](https://github.com/jeffkreeftmeijer/vim-numbertoggle) to set it up for me.  It is actually very simple:

```
augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu | set rnu   | endif
  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu | set nornu | endif
augroup END
```

**Comment by yatli** [comment]
I mean, the other end.
When the focus is lost, FVim has to send an RPC message to nvim.

**Comment by jdhao** [comment]
Thanks for the clarification.

**Comment by yatli** [comment]
Implemented. Could you have a try?
