### ISSUE TITLE
I can't type anything that isn't [a-zA-Z0-9]

### ISSUE THREAD

**Issue by Zardoz89** [yatli/fvim#115]
Can't type anything that isn't [a-zA-Z0-9]

Trying to type 'ñ' or something more usual like '~' (AltGr + 4), ^ , * + ` [ ] 

Typing ";" results in fvim writing ":"

OS: kUbuntu 19.10 
installed fvim using v0.2-186-g30d61fa dev package.

NVIM v0.3.8
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by yatli** [comment]
thanks for reporting. this is a known issue -- will need to work with upstream devs to resolve this.
tracking: #36
