### ISSUE TITLE
Underlined highlight group doesn't use defined color for underline

### ISSUE THREAD

**Issue by habamax** [yatli/fvim#117]
![image](https://user-images.githubusercontent.com/234774/73769092-267d6600-478b-11ea-861e-8bbc96f9b3df.png)

```
hi Underlined cterm=underline ctermfg=61 ctermbg=15 gui=underline guifg=#5050c0 guibg=5050c0
```

**Comment by yatli** [comment]
FVim ignores cterm* options and only uses guifg, guibg and guisp.

**Comment by habamax** [comment]
> FVim ignores cterm* options and only uses guifg, guibg and guisp.

Not sure I get it :).

If I remove all cterm* stuff it works both for gVim and neovim-qt -- underline is the same color as the text.

**Comment by yatli** [comment]
ok I get what you mean now -- underline should use fg color, if sp is not specified.

**Comment by yatli** [comment]
Current logic:
```F#
    let mutable fg = Option.defaultValue default_fg attrs.foreground
    let mutable bg = Option.defaultValue default_bg attrs.background
    let mutable sp = Option.defaultValue default_sp attrs.special
```

Your expected behavior:
```F#
    let mutable fg = Option.defaultValue default_fg attrs.foreground
    let mutable bg = Option.defaultValue default_bg attrs.background
    let mutable sp = Option.defaultValue fg attrs.special
```

I'm not sure... Feels a bit.. Asymmetric.

**Comment by habamax** [comment]
Well, it is up to you to decide in the end

**Comment by yatli** [comment]
Could you verify the behavior in gVim or nvim-qt?

**Comment by habamax** [comment]
> Could you verify the behavior in gVim or nvim-qt?

What exactly? 

Gvim

![image](https://user-images.githubusercontent.com/234774/73854864-402eb400-4844-11ea-8611-1bc74c718a3c.png)


neovim-qt
![image](https://user-images.githubusercontent.com/234774/73854929-56d50b00-4844-11ea-9de2-c6f7f37e196b.png)


vim (powershell)

![image](https://user-images.githubusercontent.com/234774/73855004-7835f700-4844-11ea-9894-3ff2e438847e.png)


nvim (powershell)
![image](https://user-images.githubusercontent.com/234774/73855042-871ca980-4844-11ea-9171-e96f63d84af2.png)

**Comment by yatli** [comment]
Thanks!
De-facto behavior compliance overrides minor "personal aesthetics" :)
