### ISSUE TITLE
Incorrect text rendering

### ISSUE THREAD

**Issue by Alex527** [yatli/fvim#12]
![Screenshot_8](https://user-images.githubusercontent.com/11727103/58122403-3d3a5780-7c12-11e9-9660-d85325da9bd2.png)
I'm having issues with text rendering. Build is latest, 0.1.130, downloaded archive, on Windows 10 with latest updates. All configuration is default with both neovim and fvim. Do I need to do some prerequisites or additional configuration?

**Comment by yatli** [comment]
Hey Alex,

You should create ginit.vim, and set the font accordingly. I haven’t decided the default fonts for all the platforms yet.

**Comment by yatli** [comment]
The neovim default cursor settings make it invisible. A workaround is added-if cursor is default highlight group, reverse it.
