### ISSUE TITLE
Alt Gr is not working / behaves like Ctrl-V

### ISSUE THREAD

**Issue by Sh3Rm4n** [yatli/fvim#123]
Hi, i have stumbled upon a weird bug.

When I'm trying to type characters which needs AltGr to be pressed (for example
the @ in the German Layout) it appears some kind escape character sequence. 

I noticed it, because I use AltGr quite heavily using the US International Layout
in Windows and Linux. 

An example using the US International Layout on Windows:

- Using US International Layout on Windows
- Opening fvim
- Going into insert mode
- Typing AltGr + q
  - This prompts with an `^` similar to using Ctrl+V in insert mode
- Typing AltGr + q again, would result into printing `<M-C-Q>` which infect is the key combination I pressed

Expected behavior:

AltGr +q should print the character `ä` when using US International Layout

When thinking about it, using AltGr behaves exactly the same as using Ctrl-V
in insert mode `:help i_CTRL-V`.

I also had confirmed this behavior on Linux, however i can not reconfirm right
now, as I do not have the machine available right now.

**Comment by Sh3Rm4n** [comment]
Reading through the issues https://github.com/yatli/fvim/issues/36 may be related.

**Comment by yatli** [comment]
Yeah. Let's track this with #36.

**Comment by yatli** [comment]
Thanks for reporting!
