### ISSUE TITLE
[Feature Request] Add command to disable builtin nerd font symbols

### ISSUE THREAD

**Issue by sainnhe** [yatli/fvim#124]
In FVim:

![img](https://user-images.githubusercontent.com/37491630/75607835-e618ca00-5b35-11ea-88c3-2aca641cb4e7.png)

As you can see, the nerd font symbols in the status line looks wired. I want to use the font patched by myself which works very well.

Alacritty + nvim + font patched by myself:

![](https://user-images.githubusercontent.com/37491630/74209833-5217b900-4c81-11ea-86e2-3727fdfc3233.png)

**Comment by yatli** [comment]
Done. A new release is pushing out.

**Comment by sainnhe** [comment]
Great work! Many thanks!!
