### ISSUE TITLE
pixelated characters , possibly related to background transparency

### ISSUE THREAD

**Issue by nree** [yatli/fvim#125]
Okay:  1a66f96553a63978849b9e168546d009643fe98f 
problem commit: 3c2d7c1e85feae33f8f730959311820c48bf8d65   (and present in latest-master)
(edit: update commits... had them in wrong order)

![Screenshot (7)](https://user-images.githubusercontent.com/12157634/76002111-1bc20800-5ed4-11ea-9edd-dede854caf68.png)

Looks like it has to do with the background. If I had a black background it wouldn't be noticeable I think.

**Comment by yatli** [comment]
Try `FVimFontSubpixel v:false`?

**Comment by nree** [comment]
No change , but `FVimFontLcdRender v:false` works

**Comment by yatli** [comment]
Ah, yes. I'm mistaking these two.
LcdRender doesn't play well with transparent background.

**Comment by yatli** [comment]
Added to the README. Thanks!

**Comment by pianocomposer321** [comment]
>Looks like it has to do with the background.

>LcdRender doesn't play well with transparent background.

I don't think it has much to do with the background being transparent. I have this problem and my background isn't transparent. You just can't see the black dots against the background when the background is also black.

**Comment by yatli** [comment]
The background is drawn on the whole canvas, while the individual glyphs have transparent background.

**Comment by yatli** [comment]
Should remove this option as it doesn't work anymore.
