### ISSUE TITLE
Colorscheme rendering issues

### ISSUE THREAD

**Issue by pianocomposer321** [yatli/fvim#132]
A picture is worth a thousand words, so here you go:

![image](https://user-images.githubusercontent.com/54072354/80023765-a91ce400-84a3-11ea-90e4-80e09aa02fe6.png)

![image](https://user-images.githubusercontent.com/54072354/80023736-9acec800-84a3-11ea-97e9-277d52a204e9.png)

As you can see, with the default colorscheme, everything's fine. But with any other colorscheme the font renders with black spots behind all the letters. I have tried :FVimFontAntialais v:true, :FVimFontAutoSnap, nothing works.

**Comment by yatli** [comment]
> all the letters

The cyan and black letters don't have the disrupted background.

What's the font being used?
I assume Windows 10, right?
Could you test other colorschemes?

Thanks!

**Comment by pianocomposer321** [comment]
> > all the letters
> 
> The cyan and black letters don't have the disrupted background.

Yeah, sorry, I forgot to mention that all the text _in the buffer_ have a disrupted background, but not any of the text in the status line.

> What's the font being used?

Whatever font is default with neovim. I renamed init.vim and ginit.vim to init.vim.old and ginit.vim.old so that it would use all the defaults so that I could be sure it wasn't something in one of those file that was causing the font rendering problems. I belive it's DejaVu Sanso Mono, but I'd have to check to be sure.

> I assume Windows 10, right?

Yes.

> Could you test other colorschemes?

I have. So far every single one that doesn't have a black background has this problem. That could even be because you just can't see the black dots against the background.

**Comment by pianocomposer321** [comment]
Also, when I do `:set cursorline`, the line that the cursor is on does not have the black dots behind the text.

**Comment by pianocomposer321** [comment]
BIG update.

I noticed that the latest update of FVim was only 16 days ago, and that this is the only issue created since then. In fact, the next lates issue was opened on Feb 16. So I tried the release that was the current one then - v0.2-192-gb6a3318 - and it worked. I thought, well maybe its just this lates release, and so I tried the next latest after v0.2-192-gb6a3318, and It _didn't_ work. So something between v0.2-192-gb6a3318 and the next one caused the bug. Anyway, I'll be using v0.2-192-gb6a3318 for now until this is fixed.

**Comment by yatli** [comment]
> I renamed init.vim and ginit.vim

An easier option is to run: `nvim -u NORC` :)

Have you enabled transparency settings? That may be the problem.

**Comment by pianocomposer321** [comment]
> Have you enabled transparency settings? That may be the problem.

I don't think so. And anyway, as I said, I renamed the init.vim and ginit.vim, so all the options would be disabled, right?

**Comment by yatli** [comment]
Ah, yes.

**Comment by yatli** [comment]
Thanks for reporting. I'll look into that when I boot back to Windows.
A clear clue is that text draw on the default background is corrupted.

**Comment by pianocomposer321** [comment]
Ok. Glad I could help (and that I can use the old version for now. I really like this project!).

**Comment by yatli** [comment]
No repro on Linux btw.

**Comment by pianocomposer321** [comment]
Interesting. What about MacOS?

**Comment by yatli** [comment]
Sold my last mac a few years ago, so "cannot repro" at the moment :p

**Comment by pianocomposer321** [comment]
Ok. But you did reproduce the issue on Windows?

**Comment by yatli** [comment]
Haven't done that yet. Running some workload on Linux.

**Comment by pianocomposer321** [comment]
Ok. Please let me know when you do try it. I'm interested to see what you find out. :)

**Comment by yatli** [comment]
Update:
![image](https://user-images.githubusercontent.com/20684720/80522524-4c4b8d00-89bf-11ea-91a7-a8a7aa50109a.png)

**Comment by yatli** [comment]
I'm very sure I've seen the pattern in your picture before. It's related to sub-pixel rendering.
But I'm not able to trigger that now. Strange.

**Comment by yatli** [comment]
see: https://github.com/yatli/fvim/issues/125

**Comment by yatli** [comment]
I've got a repro now.
It doesn't trigger on all font sizes.

![image](https://user-images.githubusercontent.com/20684720/80523155-38ecf180-89c0-11ea-99e7-d1e0c73560a5.png)

... and zoom in font one more level:

![image](https://user-images.githubusercontent.com/20684720/80523199-45714a00-89c0-11ea-84dc-307a5d20692d.png)


Try `:FVimFontLcdRender v:false'

**Comment by yatli** [comment]
Another issue I discover is that `fvim -u NORC` still loads `ginit.vim` -- bad behavior.

**Comment by pianocomposer321** [comment]
>I've got a repro now.
It doesn't trigger on all font sizes.

Interesting. Same with me, although it seems that I have to zoom in much more than you do for the pixelation to go away. I'm using JetBrainsMono NF (the JetBrains Mono nerd font. I know it doesn't need nerd fonts for the icons, but it was what was in my init.vim already, so I just kept it.)

>Try :FVimFontLcdRender v:false

👍 Works for me too.

**Comment by pianocomposer321** [comment]
>>Could you test other colorschemes?
>
>I have. So far every single one that doesn't have a black background has this problem. That could even be because you just can't see the black dots against the background.

I'm beginning to think that this has nothing to do with the colorscheme. It's just that the default background is black, so you can't see the black dots.

**Comment by yatli** [comment]
Closing this issue now. Dup of #125

**Comment by pianocomposer321** [comment]
But that issue's also closed. The problem isn't solved, is it? And the issue shouldn't be closed until it's fixed, right?

**Comment by yatli** [comment]
I've removed this config option.
