### ISSUE TITLE
fvim created an AppData folder on network %HOMEDRIVE%%HOMEPATH%

### ISSUE THREAD

**Issue by daytonb** [yatli/fvim#133]
I gave fvim just a quick try on my work laptop. I noticed that it put it's configs in `%HOMEDRIVE%%HOMEPATH%\AppData\Local\....`. On my work computer, `%HOMEDIRVE%%HOMEPATH%` is a network folder mapped to `Z:\`. fvim, should be putting things in the `%LOCALAPPDATA%` folder (`C:\Users\myusername\AppData\Local\...`).

**Comment by yatli** [comment]
Thanks for reporting.

https://github.com/yatli/fvim/blob/6b8d4723a212504cbf95c496a73a1c15a001172e/config.fs#L51

^^^ this line to blame.
