### ISSUE TITLE
fvim ssh error when connecting on external host

### ISSUE THREAD

**Issue by rayman22201** [yatli/fvim#134]
I'm running `fvim --ssh user@external.ssh.destination`

And I'm getting this unhelpful error and stack trace:
(attached a screenshot b/c I can't seem to copy and paste the text from the error dialog)
https://imgur.com/Sozdp7h

using FVim version: v0.2.240-g104449f (the latest release)

Windows 10 host.

using ssh to a local Ubuntu VM works great. But when I try this external host, it fails.

Thanks in advance for the help.

**Comment by yatli** [comment]
Are you using a key or a password?
Currently password doesn't work (no prompt to input that)

**Comment by rayman22201** [comment]
Sorry. I should have mentioned that. Yes. I'm using an ssh key. No password.

**Comment by yatli** [comment]
Is this a first-time connection (waiting for ssh thumbprint confirmation)?

**Comment by rayman22201** [comment]
Ah, ok. so this is interesting.

`ssh remote -C 'nvim --version'` does not find nvim.

But, a regular ssh session to an interactive shell works.

Interesting to note: nvim is in a slightly nonstandard path on the remote.
On the remote nvim lives in `~/.local/bin/nvim`

It looks like ssh is not setting up my PATH or loading my .bashrc at all when not running in interactive mode 😢 

I can confirm this by doing ssh remote -c "echo $PATH"

Other than the unclear error message, this seems like this is a ssh / bash config issue on my part and not an fvim issue 😄

**Comment by yatli** [comment]
`--nvim path-to-program      Use an alternative nvim program`

**Comment by yatli** [comment]
@rayman22201 does it work for you? I'm not sure if `--nvim` works for remote :p

**Comment by rayman22201** [comment]
Oh! I'm sorry. I forgot to respond. It works very well!

**Comment by yatli** [comment]
no worry, thanks for getting back.

`#case closed`
