### ISSUE TITLE
After a while, running FVim.exe doesn't work [Windows]

### ISSUE THREAD

**Issue by pianocomposer321** [yatli/fvim#136]
After a while, double-clicking FVim.exe, running from the taskbar, or cmd doesn't work. The FVim icon appears in the taskbar, but hovering over it just shows a blank (white) window. Opening a specific file (i.e. `FVim file` from cmd) still works. After moving the folder containing FVim.exe to a new location, it runs again.

**Comment by yatli** [comment]
Thanks for reporting.
Probably similar to https://github.com/yatli/fvim/issues/106 ?

**Comment by pianocomposer321** [comment]
Similar, maybe, but definitely not the same. Deleting config.json does not help.

**Comment by pianocomposer321** [comment]
Never mind, maybe deleting config.json didn't work before because FVim was running when I did it? Well, anyway, now it's working.

Another related (?) issue I've been having is that when I close FVim while in Fullscreen mode, it starts in windowed mode with the title bar above the top of my screen, so I can't reposition it. I have to delete config.json to get it back to a normal position.

What is config.json for anyway? It's not anywhere in the readme. I'm guessing it's to make the window start in the same position it was last time it was closed, but it never seems to work properly. Is there a way to disable it?

**Comment by yatli** [comment]
yeah config.json remembers some runtime configuration data, for example, pwd-window position pairs. Now there are 3 people reporting that it doesn't work, I should probably get a flag to disable that.

Could you please describe the environment you're using? I cannot repro this one though I've used FVim on a lot of devices.

**Comment by pianocomposer321** [comment]
IDK, it's not really something you can reproduce on purpose. One thing to try however, would be to open FVim, toggle fullscreen then do `:wqa`. Next time you open FVim, the title bar should be invisible. If it isn't, its possible that it's just my screen size. I have a laptop (HP EliteBook 2560p).

**Comment by yatli** [comment]
Okay, I have a repro on my machine now.

**Comment by pianocomposer321** [comment]
@yatli I have been using neovim in the terminal for some time now, so I can't give you an update on how it's working for me. I'm glad you were able to reproduce it though! I'll be interested to know what else you're able to figure out.

**Comment by yatli** [comment]
No worry, there's nothing new found on my side -- not sure how I did it...
But anyway, allow me to just hide this problem until we figure it out...

```F#
        let x, y, w, h = (int mainwin.X), (int mainwin.Y), (int mainwin.Width), (int mainwin.Height)
        // sometimes the metrics will just go off...
        // see #136
        let x, y = (max x 0), (max y 0)
        if x + w < 0 || y + h < 0
        then 0, 0, 800, 600
        else x, y, w, h
```

I've no idea why those coord queries would fail like that.
I activated RDP once though, via my android phone. The screen resolution turned into some vertical 1:2 shape and a few fvim instances were running.
