### ISSUE TITLE
FVim displaying some symbols weirdly (▶,•,❱,❰,␣,↲)

### ISSUE THREAD

**Issue by abravalheri** [yatli/fvim#137]
Hello, thank you very much for the amazing software.
I just would like to report an incident when using listchars (specially the linebreak).
Apparently there is some trouble with rendering some utf-8 chars. Please find the snapshot bellow comparing fvim (left) and nvim-qt.

```vim
set listchars=tab:▶\ ,trail:•,extends:❱,precedes:❰,nbsp:␣,eol:↲
```
![image](https://user-images.githubusercontent.com/320755/81479411-ebbc1b80-921a-11ea-8444-5dda5b9020ea.png)

(P.S.: I am using WSL on windows 10 with Ubuntu and neovim 0.4.3, Fira Code font, I have tried both installing fvim directly on windows and using the --wsl option and installing fvim directly on wsl + vcxsrv)

**Comment by yatli** [comment]
Thanks for reporting. Does it only happen with listchars, or is this a general problem about these codepoints?

**Comment by yatli** [comment]
Try `FVimFontNoBuiltInSymbols v:true " Disable built-in Nerd font symbols`

**Comment by abravalheri** [comment]
Thanks @yatli, you were really fast!
I don't know if I understood your question correctly, but it seems that these characters are displayed incorrectly regardless if they are being used as listchars, or if I input them manually the buffer.

Unfortunately, the command you indicated doesn't seem to change anything... (tested using both .deb installation and windows binary)

**Comment by yatli** [comment]
I've updated the issue title and I'll see if I can get a repro on my side.

**Comment by yatli** [comment]
More likely a font issue? I've got this:

![image](https://user-images.githubusercontent.com/20684720/81527339-90119f80-938c-11ea-9386-5a6c96e53c8f.png)

The space symbol is missing from my font (Iosevka Slab v2.x, can't remember the exact version)

**Comment by abravalheri** [comment]
Hi @yatli, thank you for the time spent in this issue.
To be sincere I have no idea how font rendering works... Indeed using Iosevka the chars seem to render properly.

But the thing is Fira (and I also tested with Ms Cascadia) are fonts that do support all those chars (indeed they are quite popular for that). Neovim-qt seem to not have any problems in rendering them... I wonder if this problem is a combination of method of rendering + specific fonts.

**Comment by yatli** [comment]
It could be that Neovim-Qt has proper font fallback -- if the symbol doesn't exist in the specified font, it falls back to one that does have support for it. Currently FVim lacks the capability.
Nevertheless, let me try with the font you mentioned. :)

**Comment by yatli** [comment]
With Cascadia I get this:

![image](https://user-images.githubusercontent.com/20684720/81565827-90318f80-93cc-11ea-88fd-0fed13bf66f1.png)

And Fira:
![image](https://user-images.githubusercontent.com/20684720/81565969-c242f180-93cc-11ea-8da5-cf92fc4fb740.png)

Are you sure these font support the codepoints? If so then this is an upstream issue, and otherwise it's a fallback mechanism issue.

**Comment by abravalheri** [comment]
Hi @yatli. I have no knowledge about font rendering so I just supposed that, since nvim-qt displays it, all the glyphs were included in the fonts, but indeed the thing you said should be the case.

Thank you very much. I will close this, since it does not seem to be a really issue.
