### ISSUE TITLE
FVim crashes while using trydaemon in Windows

### ISSUE THREAD

**Issue by aravind2612krishna** [yatli/fvim#138]
![image](https://user-images.githubusercontent.com/3424615/81497655-71080480-92dd-11ea-8f94-064caeb1e38a.png)
Above is the stack trace popup
Maybe other info : I called FVimDetach earlier

**Comment by aravind2612krishna** [comment]
Now I'm not sure if it is because I used --trydaemon, with d small instead of --tryDaemon, which doesn't crash, but doesn't produce anything either.
What I guess I'm asking for from this great GUI client is better error messages.

**Comment by yatli** [comment]
yes the --tryDaemon arg is case sensitive.
I'll think about the error handling part. Originally I hope the stacktrace will give back something useful but it looks like everyone is getting a "task was cancelled" nonsense message.

Before you start a client, did you use `fvim --daemon` to start the daemon?

**Comment by aravind2612krishna** [comment]
>fvim --daemon
>fvim --tryDaemon
opens no fvim for me, sadly.
fvim built from source Release at commit 7a2270c150c407a06

**Comment by yatli** [comment]
hmmm.. `fvim --tryDaemon` does the following things:

1. Check if a fvim daemon exists, and try to connect
2. If there's no daemon, start an embedded instance.

None of the above happens?

**Comment by aravind2612krishna** [comment]
Actually both seem to be launching an FVim now, I fail to see how to use it. 
When we use the daemon, is it to purely reduce startup time?
or does it connect to the same underlying neovim instance, and remembers buffers, windows etc, (like session opts) and allow for shared editing?

**Comment by yatli** [comment]
> or does it connect to the same underlying neovim instance, and remembers buffers, windows etc, (like session opts) and allow for shared editing?

Yes. You can use `:FVimDetach` and connect back with another client.
Or even connect two clients at the same time :)

**Comment by aravind2612krishna** [comment]
Thanks for the great app. Feel free to close this issue, as I have your attention, I'd like to ask one more question if you don't mind. Can I connect to a remote named pipe as below
`` fvim --daemon --daemonPipe fvimserver``
on Remote:
``fvim --connect \\<UNC or IP>\pipe\fvimserver``

**Comment by yatli** [comment]
I haven't tested this but had success with a tcp socket. Should be supported.
Use with caution. May have security issues.
