### ISSUE TITLE
FVim crashes when executing with --wsl flag

### ISSUE THREAD

**Issue by FilBot3** [yatli/fvim#139]
Using `FVim`
* https://github.com/yatli/fvim/releases/tag/v0.2-247-g7a2270c

with NeoVim
* https://github.com/neovim/neovim/releases/tag/nightly v0.5.0

I get the following error:

![FVim Error](https://user-images.githubusercontent.com/3039509/81962401-4d90d280-95d9-11ea-8443-c0ce4b93760e.png)

I am running on Windows 10 using Cmder running PowerShell Core 7. I would paste the text, but I can't seem to copy the text out of that window.

**Comment by yatli** [comment]
Please check the neovim installation in WSL.

**Comment by FilBot3** [comment]
I am able to access `nvim` from my terminal. Still have the same error.

**Comment by FilBot3** [comment]
Does nvim need to be installed on the WSL side as well?

**Comment by FilBot3** [comment]
I'm still having issues:

![image](https://user-images.githubusercontent.com/3039509/81976781-aa4ab800-95ee-11ea-8a7a-33cc4ba658bb.png)

**Comment by yatli** [comment]
In a wsl term:

echo $PATH
which nvim

**Comment by FilBot3** [comment]
![image](https://user-images.githubusercontent.com/3039509/82056993-542a5300-9688-11ea-8229-83e1d6c235ac.png)

**Comment by yatli** [comment]
That doesn't look like a conventional installation. For example, I've installed neovim with the unstable PPA and it ends up at `/user/bin/nvim`.
`/usr/local/nvim/bin/nvim` may not be in the path for a non-interactive session.
Do you modify the PATH variable in your `.zshrc`? I assume you're using `oh-my-zsh`.
The `--wsl` flag may not pick up the `.zshrc`, but `.bashrc` instead, but I'm not sure.
Even if for `.bashrc`, it usually skip the later part of the script if it's non-interactive (check the first few lines)

**Comment by FilBot3** [comment]
For some reason when I run `wsl nvim` it doesn't load nvim giving me `/bin/bash: nvim: command not found`, however when I login to both zsh and bash, I can run nvim. I moved the path modifications to a separate file that both `.zshrc` and `.bashrc` load. 

So, this seems to be external to FVim, and more of a WSL issue now. WSL is defaulting to Bash, but its not sourcing or loading my `.bashrc`, `.bash_profile` or `.profile` when ran that way.

**Comment by yatli** [comment]
Alright. Let's close this issue for now.

**Comment by citizen428** [comment]
@yatli I'm having a similar issue, but it doesn't seem related to not being able to find nvim.
```
# WSL
❯ which nvim
/usr/local/bin/nvim
```

```Windows
❯ wsl which nvim
/usr/local/bin/nvim
❯ FVim.exe --wsl
```

![image](https://user-images.githubusercontent.com/47985/102366367-296ff680-3feb-11eb-8bc6-4de9bc12ee67.png)

Please let me know if you'd prefer a separate issue for this.

**Comment by yatli** [comment]
That looks like a start-up error. I've seen this before when I pass incorrect params to nvim.

Try run nvim directly with wsl and see what happens?

**Comment by citizen428** [comment]
That works fine, it drops me into my normal console nvim (as you can see Powershell tab, but WSL nvim indicated by the Ubuntu icon in the status bar)/

![image](https://user-images.githubusercontent.com/47985/102367611-8c15c200-3fec-11eb-9e18-be118876fa9e.png)

**Comment by yatli** [comment]
the "unexpected byte message" is actually raw text coming from neovim. I guess it really wants to say something now that it doesn't follow the protocol :)

@citizen428 can you try latest head 9697d59 -- I've patched it so that it will print the raw message in the crash dialog on exit, like, if you do `fvim --help`:

![image](https://user-images.githubusercontent.com/20684720/102380863-6cd65f00-4003-11eb-9d68-29420d0638cb.png)

**Comment by citizen428** [comment]
Thank you @yatli, your hint " I guess it really wants to say something now that it doesn't follow the protocol :)" put me on track for a fix even before trying out the new build: I had a command in my shell init code that didn't redirect its output to `/dev/null` which caused this behavior. I appreciate you taking the time to help me figure this out, thanks!

**Comment by yatli** [comment]
noprob, I'm glad you figured it out ;)
