### ISSUE TITLE
[Linux][Pop OS] BackgroundComposition doesn't work!!

### ISSUE THREAD

**Issue by ArkjuniorK** [yatli/fvim#144]
![Screenshot from 2020-07-01 02-43-02](https://user-images.githubusercontent.com/58880821/86164638-a9d99280-bb44-11ea-96ab-0efbcc169bbe.png)

**Comment by ArkjuniorK** [comment]
FVim command for the background image and background composition not work, or it is because Linux doesn't support that feature?

**Comment by yatli** [comment]
Hi @ArkjuniorK !

Background composition only works for KDE and its derivatives. GNOME3 (and Cinnamon etc.) do not support blur behind at the moment.
