### ISSUE TITLE
nvim not in PATH with zsh as default shell

### ISSUE THREAD

**Issue by adelarsq** [yatli/fvim#145]
Opening on macOS Catalina 10.15.5 shows this:

<img width="938" alt="Captura de Tela 2020-07-02 às 11 55 48" src="https://user-images.githubusercontent.com/430272/86374716-43936380-bc5b-11ea-8f32-93829e986c26.png">

Any idea about what can be done?

**Comment by adelarsq** [comment]
There is https://github.com/yatli/fvim/issues/43. I'm using zsh but Fvim can't detect Neovim on the PATH.

**Comment by yatli** [comment]
Maybe we should take a look at other macOS nvim frontends and see how they handle the problem.

**Comment by adelarsq** [comment]
Maybe that a solution would be to provide a way to say where NeoVim installation can be found.

**Comment by yatli** [comment]
> Maybe that a solution would be to provide a way to say where NeoVim installation can be found.

This is now handled :)
