### ISSUE TITLE
Uninstall doesn't remove app associations

### ISSUE THREAD

**Issue by Kethku** [yatli/fvim#146]
I ran the install command which is great, but now I use a different vim gui. Plus it registered for file types that are kind of os breaking such as batch files etc.

Running with the uninstall command didn't remove these app associations, so now I'm stuck with a ton of file types opening fvim by default.

Is there a way to manually remove these?

**Comment by yatli** [comment]
- Check HKCR (class root) for FVim.ext entries
- I believe when these are gone, the shell will prompt for a new file association rule.

**Comment by Kethku** [comment]
The problem is that the association overwrote bat file running which kinda breaks a lot of things. Further its not obvious what to return the file association to

**Comment by yatli** [comment]
@Kethku this might help:

https://github.com/yatli/fvim/issues/68#issuecomment-532476515

In the latest version I've disabled the association for critical file types... after it revealed how many scripts should be automatically run by the IT but didn't (

**Comment by yatli** [comment]
In Windows 10, there's no "going back" for the file association in the registry. When we remove the current one, it falls back to the "Open With" dialog.

**Comment by yatli** [comment]
Let's close this one and track it in #68
