### ISSUE TITLE
:cq makes fvim hang and require force quit

### ISSUE THREAD

**Issue by brennie** [yatli/fvim#147]
## Steps to Reproduce:
1. `:cq` in normal mode

## Expected Results

fvim should quit

## Actual Results

fvim hangs and must be force quit with task manager on windows. (I haven't tested this on Linux or macOS).

**Comment by yatli** [comment]
Thanks for reporting. Can confirm the repro.

**Comment by yatli** [comment]
As there's no way to tell if it's a crash, or a `pkill nvim` or just `:1cq`, FVim now display a crash report dialog in these cases.

**Comment by yatli** [comment]
@brennie I've updated it to allow clean exit on code 1.
