### ISSUE TITLE
Issues with quoting in line-wrapped terminals?

### ISSUE THREAD

**Issue by MyriaCore** [yatli/fvim#149]
Not really sure who to submit this bug to (between fvim, nvim, or powershell). I'm having a weird issue with quoting and line-wrapping in terminal mode. This screenshot shows an attempt to quote in a wrapped line:

![image](https://user-images.githubusercontent.com/35076430/88202924-8bccf280-cc17-11ea-80d6-1f38b37c6e3f.png)

And this screenshot shows that it does actually work when the line isn't being wrapped:

![image](https://user-images.githubusercontent.com/35076430/88203143-dea6aa00-cc17-11ea-8af5-f8ce3e768872.png)

**Comment by yatli** [comment]
I had been bugged by this.
Update PSReadLine to >= 2.0 will fix this. :)

**Comment by MyriaCore** [comment]
Ah, I gotcha. Thanks, I'm not really a windows user so I didn't rly know what was going on there.
