### ISSUE TITLE
Crash on startup on Windows 10 1903

### ISSUE THREAD

**Issue by database64128** [yatli/fvim#15]
![image](https://user-images.githubusercontent.com/18757988/58630833-2d59fc00-8313-11e9-863b-6e0c6a0163aa.png)
Version: latest release

It crashes on startup when no parameters are passed. Run with `.\FVim.exe --wsl` the app quietly exits.

**Comment by yatli** [comment]
do you have `nvim` installed in WSL?

**Comment by database64128** [comment]
Installed `neovim` on WSL Ubuntu 18.04.2 LTS. Now it gives me a black window:
![image](https://user-images.githubusercontent.com/18757988/58778496-62ad6500-8605-11e9-84c5-58e273db7159.png)

**Comment by yatli** [comment]
nvim version please?

fvim requires at least v0.3.

**Comment by database64128** [comment]
thanks for your help :D
