### ISSUE TITLE
Connected daemon instance fails to run terminal [Windows]

### ISSUE THREAD

**Issue by allumik** [yatli/fvim#150]
After running `FVim.exe --daemon` and then connecting with `fvim.exe --tryDaemon` both `:term` and `:Tnew` (from kassio/neoterm) opens a new pane briefly but then shuts down. Tried different shells, did not work.

Is this related to [this issue](https://github.com/mhinz/neovim-remote/issues/133) or did i do something wrong?

**Comment by yatli** [comment]
Does `:terminal` work?

**Comment by allumik** [comment]
Nope, just shows a blank buffer which does not exit. Also restarted with blank init.vim, moved the fvim installation folder around and its still the same.

**Comment by yatli** [comment]
does this work:

`:e term://powershell`

**Comment by allumik** [comment]
Nope. 

Forgot to add that I am using nvim 0.5.0 and latest build of fvim released.

**Comment by yatli** [comment]
@allumik could you give it another try?

**Comment by allumik** [comment]
Switched computers and now on linux, so can't replicate.

**Comment by yatli** [comment]
alright. let's close it for now -- no repro on my side
