### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by PitcherTear22** [yatli/fvim#151]
I had to change `netcoreapp3.0` to `netcoreapp3.1`
`    git clone https://github.com/yatli/fvim && cd fvim && dotnet publish -f netcoreapp3.0 -c Release -r linux-x64 --self-contained`

**Comment by yatli** [comment]
yeah... recently updated.

I'll update the readme file, thanks.

**Comment by yatli** [comment]
https://github.com/yatli/fvim/commit/71992267631c57d4c3d5bc911f96513f3348032e
