### ISSUE TITLE
The command FVimFontNoBuiltInSymbols show the error

### ISSUE THREAD

**Issue by nmxiao** [yatli/fvim#157]
I use the lastest FVIM release version in windows 10.
However, when I add the command FVimFontNoBuiltInSymbols v:true into the ginit.vim, the cmd shows the error that it is not the editor command. 

my configuration file shows as below:

if exists('g:fvim_loaded')
    set guifont=Hasklug\ NF:h15
    FVimCursorSmoothMove v:true
    FVimCursorSmoothBlink v:true
    FVimUIPopupMenu v:false
    FVimFontLigature v:true
    FVimFontNoBuiltInSymbols v:true
endif

**Comment by yatli** [comment]
I just uploaded a new release: https://github.com/yatli/fvim/releases/tag/v0.2.269-gcee45d3
