### ISSUE TITLE
fvim crashes every time when I click the close button on the top right corner

### ISSUE THREAD

**Issue by jdhao** [yatli/fvim#158]
I start fvim by double click fvim.exe. When I close its window by clicking the `x` button on top right, it immediately crashes with following stack trace (I am not sure how to copy these text, so have to take a snapshot instead):

![image](https://user-images.githubusercontent.com/16662357/94109350-6bb5eb80-fe73-11ea-8581-d0d8f1a7a8a8.png)

**Comment by yatli** [comment]
What's the return code it reports? Looks like the `nvim` process did not quit cleanly.

**Comment by yatli** [comment]
hitting 'x' should be equivalent to `:qa!` so could you please also try that one.

**Comment by jdhao** [comment]
I tried several times today, and it seems not produced every time I click the `x` button. The exit code is -1073740791.

**Comment by yatli** [comment]
Could you please try `:confirm quitall`?
Just double-checked, that's what fvim uses when x is clicked.

**Comment by jdhao** [comment]
I tried the command `:confirm quitall` several times, and triggered the bug one time. The crashed can not be reproduced every time.

**Comment by yatli** [comment]
Does it trigger in terminal `nvim`?
If so, there's something in your config or nvim binary that causes the crash.

**Comment by jdhao** [comment]
Tried `:confirm quitall` in terminal nvim for more than 10 times. Can not trigger the crash for a single time. I have never observed such crash when I quit terminal nvim.

**Comment by yatli** [comment]
Thanks.
What's your nvim version? I'll see if I can find some clues.

**Comment by jdhao** [comment]
The nvim executable is downloaded from Neovim nightly release. The out of `nvim --version`:

```
NVIM v0.5.0-705-g9f704c88a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by yatli** [comment]
okay, so this version + `fvim` head, and `-u NORC`, correct? :)

**Comment by yatli** [comment]
Will get back to you when I have the results.

**Comment by jdhao** [comment]
fvim release should be v0.2.273-g41ce0c6, before the latest release (which is 4 days ago).  I started fvim by double click, it is using my nvim config for Windows. I haven't tried a clean start without any config.

I will try to reproduce without any config.

**Comment by yatli** [comment]
@jdhao I'm having some trouble building `9f704c88a`

**Comment by yatli** [comment]
@jdhao no repro on my side.

**Comment by jdhao** [comment]
@yatli  I am now using the latest version of fvim release. I can't reproduce it now.

**Comment by yatli** [comment]
okay, let's close this for now. I've been working on better error reporting/startup sequence so this may get accidentally fixed...
