### ISSUE TITLE
Click and drag with mouse should enter visual mode

### ISSUE THREAD

**Issue by MyriaCore** [yatli/fvim#159]
Clicking and dragging from normal mode should enter visual mode and select text for as long as the mouse is being held down, as is done in gVim. 

Here we could also encode common click and drag features in other editors, such as:
- double clicking before dragging mouse selects word-to-word
- triple clicking before dragging mouse selects line-to-line
- shift-clicking will select text from the cursor position to the clicked position

**Comment by yatli** [comment]
Out of box it should work mostly as you describe.
What's the behavior you see?

**Comment by MyriaCore** [comment]
When I drag, the cursor does move, but it never goes into visual mode. 

![screen-recording-2020-09-28--17-33-32](https://user-images.githubusercontent.com/35076430/94488688-10f0fc80-01b1-11eb-9919-c44218acc473.gif)

**Comment by yatli** [comment]
I guess it's a configuration problem. Check your colorscheme, mouse settings etc.

**Comment by MyriaCore** [comment]
Fair enough. I'll close this issue then.

**Comment by yatli** [comment]
Thanks.
To confirm it, you can start it with `fvim -u NORC` and then `:set mouse=a`
