### ISSUE TITLE
Disable IME on Normal Mode

### ISSUE THREAD

**Issue by luzhlon** [yatli/fvim#16]
Disable IME on Normal Mode, make fvim more perfect.

**Comment by yatli** [comment]
noted.
this is related to upstream changes in Avalonia -- people are discussing about how to couple with various IME infrastructures.

**Comment by yatli** [comment]
on Windows/Mac we may consider using im-select

@luzhlon any ideas on the Linux side? I'm away from Linux desktop for too long to remember the commands for im switching.

**Comment by luzhlon** [comment]
I also need not Linux desktop for a long time. Maybe you can try https://github.com/rlue/vim-barbaric

**Comment by yatli** [comment]
Thanks. I may need to take some time to think about this -- which way makes more sense, integrate into fvim or use a vim plugin.

`im-select` covers mac/windows, and the linux case is a bit heavier because there are multiple solutions.

We basically want a minimal interface:

```
type IM() =
    abstract Current: string option with get, set
```

**Comment by yatli** [comment]
actually this might not be the intended default setting, suppose in normal mode we type:
```
f哈
```
we should find `哈` rather than `h`
