### ISSUE TITLE
Completion (window?) causes lag

### ISSUE THREAD

**Issue by hnry** [yatli/fvim#160]
Notice fvim struggles to keep up with typing, it gets so bad I even lose input (ex: if I type abcdef, I'll get adef sometimes).

I realize the problem it has to do with completion (using coc.vim). I don't think it has to do with completion itself, but the pop up. Every time I get completion and the pop up window shows it'll begin to lag. 

Windows 10, Nvim 0.4.4, latest fvim master (but experiences this in previous builds), no wsl.

No issues using nvim in cmd, windows-terminal, with same vim config & setup. Just happens in fvim.

**Comment by hnry** [comment]
I fixed it by `suggest.maxCompleteItemCount: 10`, default is 50.` Either it doesn't like drawing that many items on the drop down list or ? I don't know.

But here is another issue, the description window falls behind the dropdown so it is difficult to read.
Expected: Properly size the window and place it left or right of the dropdown. This is what I'm use to when using nvim with terminal.

![Screenshot (94)](https://user-images.githubusercontent.com/25837/94823028-5e4bb480-03d1-11eb-8274-1330a04d09c2.png)

**Comment by hnry** [comment]
`FVimUIPopupMenu v:false` fixes issue with lag and overlapping

**Comment by yatli** [comment]
Hi @hnry, thanks for reporting.
I'm reopening this because `FVimUIPopupMenu` is still flawed.

The overlap problem is fixed upstream, here: https://github.com/neovim/neovim/pull/11943

The lag problem is related to the UI framework. I'll have to do some profiling to see how to improve the performance.

**Comment by yatli** [comment]
no lag issue for me for more than a year -- safe to close?
