### ISSUE TITLE
When start excute fvim on win10 , it crashes 

### ISSUE THREAD

**Issue by techfisha** [yatli/fvim#162]
![1](https://user-images.githubusercontent.com/72426766/95190545-129a7000-0802-11eb-86b8-37cc7ed294a5.png)

v0.2.273 and 0.2.269 ,both win-x64 and win7-x64 the same issues on  win10 2004.

**Comment by yatli** [comment]
`nvim` not on your `%PATH%`?

**Comment by techfisha** [comment]
Oh, I see. Thank you very much.
