### ISSUE TITLE
Rendering glitches -- font glyphs drawn out of the cell bounds

### ISSUE THREAD

**Issue by jdhao** [yatli/fvim#164]
I am using fvim on Windows 10. I have noticed that fvim will show some glitches when I close another neovim window.

Steps to reproduce:

+ Open fvim： `fvim -u NORC test.py`
+ open the help window: `:h help`.
+ Close the help window: `:quit`.

Notice carefully that the previous fvim window has some noticeable glitches on the screen. Of course, using `Ctrl-L` will redraw the screen and clear them. But it is a little annoying.

P.S.: I can not reproduce this behavior when using nvim-qt using the same steps.

**Comment by yatli** [comment]
Hi @jdhao thanks for reporting. I've been bugged by this too and it's font-specific.
With `Iosevka Slab:h16` it does not repro with -NORC, but the problem still exists, especially for powerline symbols -- the glyphs are drawn out of the box.

A potential workaround is `:FVimFontLineHeight "+1"` (or -1, depends on your font)

I've yet to find a solution to this. Sometimes I adjust it so that it's good for one font but another breaks 😂

**Comment by jdhao** [comment]
I am using `Hack:h13` for fvim. Unfortunately, the trick does not work for me.🐈

**Comment by yatli** [comment]
Could you capture a screenshot? If that doesn't work it may be a different issue.

**Comment by jdhao** [comment]
This is the glitch I mean: https://imgchr.com/i/BJcu0f.  And fvim is started using `fvim -u NORC test.md`.

My config in ginit.vim for fvim:

```
if exists('g:fvim_loaded')
  set termguicolors
  " colorscheme gruvbox8_hard
  set guifont=Hack:h13
  " Cursor tweaks
  FVimCursorSmoothMove v:true
  FVimCursorSmoothBlink v:true

  " Background composition, can be 'none', 'blur' or 'acrylic'
  FVimBackgroundComposition 'blur'
  FVimBackgroundOpacity 1.0
  FVimBackgroundAltOpacity 1.0

  " Title bar tweaks (themed with colorscheme)
  FVimCustomTitleBar v:true

  " Debug UI overlay
  FVimDrawFPS v:false
  " Font debugging -- draw bounds around each glyph
  FVimFontDrawBounds v:false

  " Font tweaks
  FVimFontAntialias v:true
  FVimFontAutohint v:true
  FVimFontHintLevel 'full'
  FVimFontSubpixel v:true
  FVimFontLigature v:true
  " can be 'default', '14.0', '-1.0' etc.
  FVimFontLineHeight 'default'

  " Try to snap the fonts to the pixels, reduces blur
  " in some situations (e.g. 100% DPI).
  FVimFontAutoSnap v:true

  " Font weight tuning, possible values are 100..900
  FVimFontNormalWeight 100
  FVimFontBoldWeight 700

  FVimUIPopupMenu v:false
endif
```

**Comment by jdhao** [comment]
@yatli  sorry, I am doing it wrongly. I was using `:FVimFontLineHeight +1` instead of `:FVimFontLineHeight "+1"`.  Using `:FVimFontLineHeight "+1"` fix the issue for me.

what is the difference between using the double quote and no double quote? I thought wrongly that they are the same...  Fvim did not give any error when I omit the double quote.

**Comment by yatli** [comment]
It's number vs string :)

`:FVimFontLineHeight "+1"` -- relative height +1, based on font height
`:FVimFontLineHeight "16"` -- absolute height 16

Cannot distinguish the two with numbers.

**Comment by yatli** [comment]
@jdhao should be fixed now

**Comment by jdhao** [comment]
Thanks, will try tomorrow.

**Comment by jdhao** [comment]
@yatli  It seems that this commit hasn't been included in the latest release.

**Comment by yatli** [comment]
try 0.2.306 😅

**Comment by jdhao** [comment]
@yatli  The newest release seems to have fixed the rendering glitch. Tried with `fvim -u NORC`.

**Comment by yatli** [comment]
glad it really works!

**Comment by yatli** [comment]
Version 0.2 is reaching a stable state.
I will be bumping the version to 0.3 once Avalonia v0.10 reaches GA
