### ISSUE TITLE
First open error

### ISSUE THREAD

**Issue by AlphaTechnolog** [yatli/fvim#168]
I was open a fvim at first time but i give the next error:
![Captura de pantalla de 2020-11-08 19-30-06](https://user-images.githubusercontent.com/54639968/98487441-41d54000-21f9-11eb-9be0-a20c2aa4e50c.png)
Help me please!

**Comment by yatli** [comment]
Hi!

I assume you're running Linux (from the look of the window border).
Could you please provide:

- Your `$PATH`
- Your `nvim --version`?

Thanks.

**Comment by AlphaTechnolog** [comment]
My path is: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/node-v12.18.2-linux-x64/bin/:/home/guerrafs/.local/bin/:/home/guerrafs/.config/composer/vendor/bin/

My neovim version is: 0.1.7

**Comment by yatli** [comment]
> My neovim version is: 0.1.7

That's an ancient version, amigo.
FVim requires nvim 0.4+

The exception isn't properly translated to a hint message though. I'll fix that.

**Comment by yatli** [comment]
Error reporting should reflect the problem as of https://github.com/yatli/fvim/commit/31f30c09ec91783b801a99c6079ca46b8b09be70
