### ISSUE TITLE
Slow window drag response

### ISSUE THREAD

**Issue by Martin-Nyaga** [yatli/fvim#169]
I've been using FVim as my daily driver for a week or two now, and I'm enjoying it. The renderinig is crisp and fast 👌.

However, I'm having a strange problem. When I click on the title bar and drag the window, it does not move at the same speed as I am moving my mouse, and instead moves much slower. When dragging any other window (or moving my mouse free-form), the mouse moves at the normal speed. But when dragging the FVim window, the mouse speed becomes really slow. It's a little difficult to demonstrate this, but let me know if there is any additional information I can provide.

I am on Windows 10, I'm running `FVim.exe --wsl`. NVIM version: v0.5.0-694-g4a2618c81

**Comment by yatli** [comment]
Hi!

This is a limitation of win10 acrylic background composition. The workaround is to switch to 'blur', 'transparent' or 'none'.
Until win10 gives us documented way to bring win32 acrylic on par with uwp...

**Comment by Martin-Nyaga** [comment]
Fantastic, solved! 👍
