### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound] - "KB2533623"

### ISSUE THREAD

**Issue by MrCull** [yatli/fvim#172]
The markup version of the readme that is displayed for the main page in this repo contains the following bad link:

"KB2533623"
Status code [404:NotFound] - Link: https://www.microsoft.com/en-us/download/details.aspx?id=26764

After a bit of Googling I found this page where this KB is discussed with possible alternates which might help here(??): https://github.com/dotnet/docs/issues/20459

**Extra**

This bad link was found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder

Re-check this Repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fyatli%2ffvim
Check all Repos for this GitHub account: http://githubreadmechecker.com/Home/Search?User=yatli

--

I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback, or log an “Issue”.

**Comment by yatli** [comment]
Thanks! Fixed with https://github.com/yatli/fvim/commit/970d45d77670006afd3605da409c5f6cb950c88b and later commits.
