### ISSUE TITLE
Bad integration with FZF plugin

### ISSUE THREAD

**Issue by bsjaramillo** [yatli/fvim#179]
When escape from FZF, the pop up its not closing.
And how i config the keyboard for my region (Latinoamerica) ?
![image](https://user-images.githubusercontent.com/33032851/114077335-4d429b00-986d-11eb-9206-fb424087c919.png)

**Comment by yatli** [comment]
could you try again? been fixing a lot of issues around this

**Comment by bsjaramillo** [comment]
its ok now, but the keyboard distribution is not the same like vim, i mean, to get the commands

**Comment by yatli** [comment]
okay. closing this one.

the master thread for the keyboard mapping problem: https://github.com/yatli/fvim/issues/36
