### ISSUE TITLE
Make release zip have a root folder

### ISSUE THREAD

**Issue by omerhijazi404** [yatli/fvim#186]
Your release zip files have the files directly at the root, so when i was extracting i ruined my desktop thinking it would be another folder as a root  
So It'd be better if you do it like this:
fvim-win-x64.zip
└───fvim-win-x64
instead of
fvim-win-x64.zip
└───(files)

**Comment by yatli** [comment]
You can use chocolatey for installation if you don't want to deal with the zip balls...

**Comment by omerhijazi404** [comment]
Alright sure
