### ISSUE TITLE
How can I make my FVim installation look like the one on the readme

### ISSUE THREAD

**Issue by omerhijazi404** [yatli/fvim#187]
I want an FVim config so that it will look like the one on the readme.

![](https://github.com/yatli/fvim/raw/master/images/screenshot.png)

**Comment by omerhijazi404** [comment]
@yatli

**Comment by omerhijazi404** [comment]
Anyone??? @yatli? @v-yadli?

**Comment by yatli** [comment]
hi @omerhijazi404 !

Sorry for the late response. Here's the ingredient:

- Iosevka Slab
- FVimBackgroundImageOpacity 0.3
- https://github.com/v-yadli/vimrc/blob/master/image/W2.jpg as background image to give it a grainy feeling
- vim-airline
- `pencil` theme
- Acrylic

**Comment by omerhijazi404** [comment]
Thanks!
