### ISSUE TITLE
Awkward looking font when attaching to a WSL Neovim

### ISSUE THREAD

**Issue by shanoaice** [yatli/fvim#193]
When I was using the `--wsl` option to attach to a WSL Neovim, the font looks really awkward (not really the monospaced font I've set in the `ginit.vim` and they all shrinked together)

Screenshot:
![image](https://user-images.githubusercontent.com/25174488/127500563-8e8fe0b3-93d5-46eb-b35f-70bf37e2bf98.png)

This is the `ginit.vim` content:
![image](https://user-images.githubusercontent.com/25174488/127500718-c3d296dc-3d09-41b0-94b7-eeba1733461d.png)

**Comment by shanoaice** [comment]
I've find out the problem...the configuration in the `init.lua` seemed to have set `guifont` too and caused a conflict. Is there any way to solve this? I sometimes do need to set a globally avaliable font...

**Comment by yatli** [comment]
hmm, could you double-check -- `set guifont=` requires a height specification for example `FontName:h14`

**Comment by yatli** [comment]
The latest HEAD changes the behavior to fall back to the OS default.
