### ISSUE TITLE
Local clipboard with FVim remoting

### ISSUE THREAD

**Issue by gsuuon** [yatli/fvim#195]
Is there already some way to use the client / local system clipboard in an fvr session? If not, consider this a feature request - I can take a crack at adding it. Thanks!

**Comment by yatli** [comment]
could be related to this: https://github.com/neovim/neovim/issues/13331

and I have a (weird) workaround -- `:checkhealth`, and it will detect the FVim clipboard provider. :)

**Comment by yatli** [comment]
Fixed in https://github.com/yatli/fvim/commit/2d9ea840b3ae7e1d9db17b73c7ad42c28bccd22e
