### ISSUE TITLE
Strange display effect

### ISSUE THREAD

**Issue by LinHQ1999** [yatli/fvim#196]
- Neovim: v0.5
- Fvim: Latest release
- OS: Windows10 21H1

ginit.vim

```vim
if exists('g:GuiLoaded')
    GuiFont! FiraCode NF:h14
    GuiPopupmenu 0
    GuiTabline 0
    " 当前版本 nvim-qt 不可用
    "GuiAdaptiveStyle fusion
elseif exists('g:fvim_loaded')
    set guifont=FiraCode\ NF:h14
    "set guifont=Iosevka\ Slab:h14
    FVimCursorSmoothMove v:true
    FVimCursorSmoothBlink v:true
endif
```
The result is
![image](https://user-images.githubusercontent.com/50328516/130674237-9fe97d7e-d423-41d2-8f5a-196e7d610dd2.png)
![image](https://user-images.githubusercontent.com/50328516/130674291-9a516ca6-2358-4442-ab76-75fbe90ec41b.png)

**Comment by yatli** [comment]
Font issue -- I should probably warn and set a fallback.
