### ISSUE TITLE
No text rendered in telescope popup

### ISSUE THREAD

**Issue by raghur** [yatli/fvim#199]
So upgraded to latest and telescope no longer shows any text 

![2021-09-08_0926](https://user-images.githubusercontent.com/516267/132444492-e56a1f63-9e23-4e47-b64c-8016e246dbcd.png)

reverting to  `0.2.349+9f6430d-43-g646a86f` and all seems to be well. I also tried `0.2.392+g646a86f-20-g3b521db` - but that has the same problem too.

Is there anything I should try? or do I need any additional config?

Env: KDE Neon 5.22 (Ubuntu 20.04), Nvidia drivers

**Comment by yatli** [comment]
noted, thanks!
I've also encountered this today with coc.nvim.

**Comment by yatli** [comment]
Are you saying that this problem also exists in 0.2.x? Then it's not related to the new multigrid (and will be easier to debug!)
Turning on FVimFontDrawBounds reveals that no text rendering is done in the floating window:

![image](https://user-images.githubusercontent.com/20684720/132744522-50d3c738-b555-4ec6-9dbe-48996d63e5c7.png)

**Comment by yatli** [comment]
It should exist in 0.2.x if you're running with multigrid.
Confirmed it's a z-order issue.

**Comment by citizen428** [comment]
@yatli I still seem to have this issue with v0.3.489+g98c4036.
![image](https://user-images.githubusercontent.com/47985/140601100-62763c50-61d6-4cff-a5c7-fe5a48e3da64.png)

**Comment by yatli** [comment]
uh oh here we go again. reopening.

**Comment by 13k** [comment]
Same here.

OS: Fedora Linux 35 x86_64
Kernel: 5.16.8-200.fc35.x86_64
DE: KDE Plasma 5.23.5
WM: kwin (Wayland)
GPU: AMD Navi 21, driver: amdgpu

![20220215-171327](https://user-images.githubusercontent.com/4762/154141569-09b7de34-7373-4c48-a0c2-3c9706058779.png)

**Comment by TheLazyLemur** [comment]
I can confirm that I have this same issue when running Neovim 0.7 on both Ubuntu and Windows.

**Comment by yatli** [comment]
To begin attacking this bug, I'll prepare a version that draws the z index of each window. Please attach pictures so I can identify the problem.

**Comment by yatli** [comment]
![image](https://user-images.githubusercontent.com/20684720/158244895-153e8a7e-efce-4639-9d51-6d4cb3ea093e.png)

I don't know... This conflicts with the current logic:

- Sort by z-order
- Tie = sort by creation seq

Clearly, the content is being wiped out by the outer frame.

**Comment by yatli** [comment]
https://github.com/yatli/fvim/commit/2c1625bdb2b6acf7e547e0b6b7f07b366794a3b1?diff=unified#diff-279af2dd9ccff73c764c6abc2f3f81d266fdda9428638a0f6be7bf9f4030c62cL838-R838

Me cannot sort. 😅
