### ISSUE TITLE
deb package version wrong. 

### ISSUE THREAD

**Issue by songww** [yatli/fvim#200]
fvim-linux-amd64.deb downloaded from release `v0.3.433+gf48ac0e`, but version is `0.3.423+g6e28667-10-gf48ac0e`after install.

**Comment by yatli** [comment]
😱

**Comment by yatli** [comment]
strange... `git describe` returns incremental versions from 0.3.433, which means the tags are added correctly.

**Comment by yatli** [comment]
I see what's happening. Tags are pushed after the ci build!
