### ISSUE TITLE
LunarVim rendering issues

### ISSUE THREAD

**Issue by cro** [yatli/fvim#205]
I appreciate the look of FVim over neovim-qt, really nice job!  

I'm seeing something odd when trying to adopt the LunarVim configs.  On startup I appear to get a variable-width font, which isn't a big deal, I can `set guifont` fine.  But the LunarVim popups appear to be cut off.

On startup:
<img width="637" alt="Screen Shot 2021-10-14 at 10 10 18 AM" src="https://user-images.githubusercontent.com/83323/137355946-8bb33c3f-c18b-46c5-93e1-8d7ba1335306.png">

After `set guifont=Hack:h14`

<img width="636" alt="Screen Shot 2021-10-14 at 10 11 23 AM" src="https://user-images.githubusercontent.com/83323/137356091-b2ec15e1-5db3-4f8c-9d55-61863b1b8090.png">

After pressing Space to get the standard popup menu:

<img width="635" alt="Screen Shot 2021-10-14 at 10 12 23 AM" src="https://user-images.githubusercontent.com/83323/137356257-a9615b26-0666-41fd-b4a1-df58b0b9f512.png">

Expected result (screenshot from neovim-qt):

<img width="794" alt="Screen Shot 2021-10-14 at 10 16 18 AM" src="https://user-images.githubusercontent.com/83323/137356880-70fa51a4-5bef-493b-b589-8fc3ab26c90d.png">

**Comment by yatli** [comment]
Should be fixed in the latest release.

**Comment by tobealive** [comment]
Finding fvim is like finding a brick of gold. Can't believe my eyes how impressive it is.

I'm not using lunarvim but also have the problem that floating windows like whichkey are displaced.

Would love to use fvim as main editor.

**Comment by yatli** [comment]
@tobealive which version are you on?

I may have to try "whichkey" myself.

**Comment by yatli** [comment]
Problem identified.
This plugin properly implements 'anchor to bottom' which I did not implement back then.

**Comment by yatli** [comment]
https://dev.azure.com/v-yadli/fvim/_build/results?buildId=701&view=results

This is better

**Comment by tobealive** [comment]
> @tobealive @cro https://dev.azure.com/v-yadli/fvim/_build/results?buildId=700&view=results
> 
> When the build finishes, you can access built artifacts for your platform -- in the "Jobs" section, click the platform, go to the build logs, then there's a "download artifact" in the log. Really accessible (TM).

Oh nice, I didn't quiet understood that yesterday and thought I'll need to build it from source. Didn't come a lot in contact with azure yet. That's very nice. Thank you.

**Comment by yatli** [comment]
https://dev.azure.com/v-yadli/fvim/_build/results?buildId=701&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by tobealive** [comment]
The right part of the floating anchored window is cut off a little, so the border is missing. That's not a thing that really bothers me and there are probably more important things for that development phase.
![Screenshot_20220323_102001](https://user-images.githubusercontent.com/34311583/159666493-cef67691-6125-46ff-ae02-91d106b01b52.jpg)

Probably another thing that is related to the opened issue and is also visible on the screenshot is the error displaying icons and just showing those boxes.

It's possible to solve this by conditionally assigning other icons to fvim. But there is probable a more elegant solution to this. It's the codicons pack which has trouble being displayed in fvim.

**Comment by yatli** [comment]
When you have time, you can try clone the repo and run in debug mode: `dotnet run`
This will give you extra info on the window layout (like in my screenshot)

And btw, do please try this:
https://github.com/yatli/fvim/blob/master/ViewModels/CompletionItemViewModel.fs

Replace your completion icons with these text characters (yes just text) and they will be shown graphically in FVim.

Check `Assets/intellisense` for the icons, and I believe you can even hack them for customization.

**Comment by yatli** [comment]
Could you copy pasta the lua code snippet for icon configuration? I'd like to paste it in and debug.

I believe I've done something similar for coc.nvim and it displays fine (

**Comment by yatli** [comment]
wait, it displays fine in comments but not in code?

![image](https://user-images.githubusercontent.com/20684720/159675373-4707fe43-a8a6-460e-af37-2564e14bbecf.png)

**Comment by tobealive** [comment]
Nope this comment is a leftover from the icons above.  

here the full icons lua can you use it like that?
```lua
-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
if vim.fn.has "mac" == 1  then
  -- elseif vim.fn.has "mac" == 1 then
  return {
    kind = {
      Text = "",
      -- Method = "m",
      -- Function = "",
      -- Constructor = "",
      Method = "",
      Function = "",
      Constructor = "",
      Field = "",
      -- Variable = "",
      Variable = "",
      Class = "",
      Interface = "",
      -- Module = "",
      Module = "",
      Property = "",
      Unit = "",
      Value = "",
      Enum = "",
      -- Keyword = "",
      Keyword = "",
      -- Snippet = "",
      Snippet = "",
      Color = "",
      File = "",
      Reference = "",
      Folder = "",
      EnumMember = "",
      Constant = "",
      Struct = "",
      Event = "",
      Operator = "",
      TypeParameter = "",
    },
    type = {
      Array = "",
      Number = "",
      String = "",
      Boolean = "蘒",
      Object = "",
    },
    documents = {
      File = "",
      Files = "",
      Folder = "",
      OpenFolder = "",
    },
    git = {
      Add = "",
      Mod = "",
      Remove = "",
      Ignore = "",
      Rename = "",
      Diff = "",
      Repo = "",
    },
    ui = {
      Lock = "",
      Circle = "",
      BigCircle = "",
      BigUnfilledCircle = "",
      Close = "",
      NewFile = "",
      Search = "",
      Lightbulb = "",
      Project = "",
      Dashboard = "",
      History = "",
      Comment = "",
      Bug = "",
      Code = "",
      Telescope = "",
      Gear = "",
      Package = "",
      List = "",
      SignIn = "",
      Check = "",
      Fire = "",
      Note = "",
      BookMark = "",
      Pencil = "",
      -- ChevronRight = "",
      ChevronRight = ">",
      Table = "",
      Calendar = "",
    },
    diagnostics = {
      Error = "",
      Warning = "",
      Information = "",
      Question = "",
      Hint = "",
    },
    misc = {
      Robot = "ﮧ",
      Squirrel = "",
      Tag = "",
      Watch = "",
    },
  }
elseif(vim.g.fvim_loaded) then
  return {
    kind = {
      Text = " ",
      -- Method = "m ",
      -- Function = " ",
      -- Constructor = " ",
      Method = " ",
      Function = " ",
      Constructor = " ",
      Field = " ",
      -- Variable = " ",
      Variable = " ",
      Class = " ",
      Interface = " ",
      -- Module = " ",
      Module = " ",
      Property = " ",
      Unit = " ",
      Value = " ",
      Enum = " ",
      -- Keyword = " ",
      Keyword = " ",
      -- Snippet = " ",
      Snippet = " ",
      Color = " ",
      File = " ",
      Reference = " ",
      Folder = " ",
      EnumMember = " ",
      Constant = " ",
      Struct = " ",
      Event = " ",
      Operator = " ",
      TypeParameter = " ",
    },
    type = {
      Array = " ",
      Number = " ",
      String = " ",
      Boolean = "蘒 ",
      Object = " ",
    },
    documents = {
      File = " ",
      Files = " ",
      Folder = " ",
      OpenFolder = " ",
    },
    git = {
      Add = " ",
      Mod = " ",
      Remove = " ",
      Ignore = " ",
      Rename = " ",
      Diff = " ",
      Repo = " ",
    },
    ui = {
      Lock = " ",
      Circle = " ",
      BigCircle = " ",
      BigUnfilledCircle = " ",
      Close = " ",
      NewFile = " ",
      Search = " ",
      Lightbulb = " ",
      Project = " ",
      Dashboard = " ",
      History = " ",
      Comment = " ",
      Bug = " ",
      Code = " ",
      Telescope = " ",
      Gear = " ",
      Package = " ",
      List = " ",
      SignIn = " ",
      Check = " ",
      Fire = " ",
      Note = " ",
      BookMark = " ",
      Pencil = " ",
      -- ChevronRight = " ",
      ChevronRight = "> ",
      Table = " ",
      Calendar = " ",
    },
    diagnostics = {
      Error = " ",
      Warning = " ",
      Information = " ",
      Question = " ",
      Hint = " ",
    },
    misc = {
      Robot = "ﮧ ",
      Squirrel = " ",
      Tag = " ",
      Watch = " ",
    },
  }
else
  --   פּ ﯟ   蘒練 some other good icons
  return {
    kind = {
      Text = " ",
      Method = " ",
      Function = " ",
      Constructor = " ",
      Field = " ",
      Variable = " ",
      Class = " ",
      Interface = " ",
      Module = " ",
      Property = " ",
      Unit = " ",
      Value = " ",
      Enum = " ",
      Keyword = " ",
      Snippet = " ",
      Color = " ",
      File = " ",
      Reference = " ",
      Folder = " ",
      EnumMember = " ",
      Constant = " ",
      Struct = " ",
      Event = " ",
      Operator = " ",
      TypeParameter = " ",
      Misc = " ",
    },
    type = {
      Array = " ",
      Number = " ",
      String = " ",
      Boolean = " ",
      Object = " ",
    },
    documents = {
      File = " ",
      Files = " ",
      Folder = " ",
      OpenFolder = " ",
    },
    git = {
      Add = " ",
      Mod = " ",
      Remove = " ",
      Ignore = " ",
      Rename = " ",
      Diff = " ",
      Repo = " ",
    },
    ui = {
      Lock = " ",
      Circle = " ",
      BigCircle = " ",
      BigUnfilledCircle = " ",
      Close = " ",
      NewFile = " ",
      Search = " ",
      Lightbulb = " ",
      Project = " ",
      Dashboard = " ",
      History = " ",
      Comment = " ",
      Bug = " ",
      Code = " ",
      Telescope = " ",
      Gear = " ",
      Package = " ",
      List = " ",
      SignIn = " ",
      Check = " ",
      Fire = " ",
      Note = " ",
      BookMark = " ",
      Pencil = " ",
      ChevronRight = "",
      Table = " ",
      Calendar = " ",
    },
    diagnostics = {
      Error = " ",
      Warning = " ",
      Information = " ",
      Question = " ",
      Hint = " ",
    },
    misc = {
      Robot = " ",
      Squirrel = " ",
      Tag = " ",
      Watch = " ",
    },
  }
end
```

**Comment by yatli** [comment]
alright got repro:

![image](https://user-images.githubusercontent.com/20684720/159680578-944a4761-9649-4626-a846-e237645deb65.png)

**Comment by yatli** [comment]
Are they part of NERD font?
I may have to update it.

**Comment by tobealive** [comment]
I not 100%  sure but i think they are not. Got them from an nvim from scratch series and hadn't had problems with them yet i other scenarios. I think lunarvim is using the same icons though probably that's why the thread starter also having those issues.

**Comment by yatli** [comment]
That lunarvim logo looks like braille to me.

**Comment by yatli** [comment]
``
https://utf8-icons.com/utf-8-character-60051
It displays as a battery icon on my side:

![image](https://user-images.githubusercontent.com/20684720/159904840-02e6e6ff-637b-40e8-bb3f-18111f937c3c.png)

This is clearly the windows 10 power tray icon. Probably not what you want?

**Comment by yatli** [comment]
Okay, EA93 is a part of `(0xEA60u, 0xEBEBu)  // Codicons`
New NERD font.

**Comment by tobealive** [comment]
Hey, sorry the late response.

wanting to start into vacation this evening and having ongoing projects, the office is trying to squeeze out the rest of the energy that is left inside of me.

haha a mahjong block sounds cool to me.
An `abc` symbol would be the intended one.
![abc](https://user-images.githubusercontent.com/34311583/159937962-d4f6e9e3-ffb2-4a9a-89df-282def0bf087.jpg)

Oh great insight and starting point of a real fix.

**Comment by yatli** [comment]
@tobealive https://dev.azure.com/v-yadli/fvim/_build/results?buildId=706&view=results
will be ready to download soon.

**Comment by yatli** [comment]
Version 0.3.528 released. Should've fixed everything related to this thread.
Case closed. 😎
