### ISSUE TITLE
Windows 11 Fvim :set guifontwide invalid

### ISSUE THREAD

**Issue by ayehome** [yatli/fvim#216]

**Comment by yatli** [comment]
Can you elaborate?

**Comment by ayehome** [comment]
My fault,
Modify :set guifontwide=YaHei:h14:cgb2312 to :set guifontwide=YaHei:14   Settings take effect

**Comment by ayehome** [comment]
It's Gvim feature

**Comment by ayehome** [comment]
yes. 
It's GVIM's behavior, Use :h gui-font to view, Specific Win32.


Can you say Chinese?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yatli/fvim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月11日(星期五) 晚上10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yatli/fvim] Windows 11 Fvim :set guifontwide invalid (Issue #216)





 
ooh. I didn't know one can specify encoding for gfw -- original gvim behavior?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
