### ISSUE TITLE
multigrid

### ISSUE THREAD

**Issue by yatli** [yatli/fvim#22]

**Comment by yatli** [comment]
We're making progress -- now the child windows can be properly anchored to the parent.
However, it appears that multigrid depends on some other functionalities -- maybe external completion menu.
The observation is that, with multigrid enabled, neovim crashes as soon as I start to type a seen word (thus triggering the completion menu).

Therefore this should be done after #33, and possibly #32 .

**Comment by Kethku** [comment]
Can you give some more information about what this feature would enable? I'm very curious. Will this give us multiple fvim frames connected to the same neovim instance? Multi monitor?

**Comment by yatli** [comment]
The `ext_multigrid` feature places each window in a separate grid (vs. now all windows are placed in one grid) -- each grid can then be displayed in a separate UI. Also, there's an upstream PR that treats each vim tab as a separate grid. So multi monitor yes, multi frames yes. (NeoVim Yes! :D )

**Comment by yatli** [comment]
tracking: #79

**Comment by yatli** [comment]
#79 end up not working out. reopening this.

**Comment by yatli** [comment]
done. 🎉
