### ISSUE TITLE
Some mapping works incorrectly

### ISSUE THREAD

**Issue by damanis** [yatli/fvim#221]
Configure 'alias' of ':' vim.api.nvim_set_keymap('', '<A-x>', ':', {})
Then, when press alt-x the command line looks as ':x' ('x' always added) instead of ':'
There is no problem in fvim-linux-amd64-v0.3.501+g76a08f0-2-g5254e85

**Comment by yatli** [comment]
Can confirm, thanks for reporting.
This issue is due to inconsistencies in keyboard event handling across different platforms.
I'll see if I can fix this issue upstream.
Until then, a fvim patch is needed.

**Comment by damanis** [comment]
I don't know if it related: yank command does not update both PRIMARY and SECONDARY clipboards in linux.
Configuration: vim.o.clipboard = [[unnamed]]

**Comment by yatli** [comment]
https://github.com/yatli/fvim/blob/8a6f26b9f92cfd9b3c491a29256cad2435ec7348/model.fs#L403-L410

I'm not familiar with the X11 clipboard behavior, and I'm depending on upstream Avalonia capabilities on this.
