### ISSUE TITLE
这个问题你可以删除

### ISSUE THREAD

**Issue by ayehome** [yatli/fvim#223]
我想问一下，不考虑使用 gitee.com 这一类的国内平台做一个镜像吗? 访问github.com 真的很累，我对github的使用很简单，通过github的mirror完全可以满足，因此也对VPN无需求。我想我这情况的人应该有不少的。

**Comment by yatli** [comment]
目前不考虑，我维护不过来。

**Comment by yatli** [comment]
之前知乎上说有国内的加速站（不是镜像）？
