### ISSUE TITLE
Latest release has old version number in file names

### ISSUE THREAD

**Issue by tech189** [yatli/fvim#224]
E.g., fvim-win-x64-v0.3.**_528_**+g5190942-2-gc43c0c6.zip should be v0.3.**_530_**.

Noticed this because the Scoop package can't get the latest version as it is looking for the correctly named file.

**Comment by yatli** [comment]
Thanks! The CI pipeline messed up. I'm scheduling a new run now.

**Comment by tech189** [comment]
All fixed now, thanks!
