### ISSUE TITLE
Floating window positioning regression

### ISSUE THREAD

**Issue by yatli** [yatli/fvim#225]
Happens to my latex session yesterday, the linting error popup is stuck at root grid 0,0
Can't repro at the moment...

**Comment by carbidecodes** [comment]
I'm running into something maybe related - preview windows which span the entire size of the editor are positioned with the top right corner under the cursor.
Here's what I see in the default Neovim gui:
![image](https://user-images.githubusercontent.com/102993453/161820775-11d58157-a286-4410-8458-e16003b21d63.png)
And here's what I'm getting in FVim:
![image](https://user-images.githubusercontent.com/102993453/161820829-db908de8-5df7-43d7-a830-74dbe2fa1924.png)

**Comment by carbidecodes** [comment]
I'm still seeing the positioning problem in the newest release so maybe it wasn't related, should I open a separate issue for it?

**Comment by yatli** [comment]
yes, please do!
