### ISSUE TITLE
Copy/paste from local system clipboard via remote FVim

### ISSUE THREAD

**Issue by MrPeterLee** [yatli/fvim#228]
Hi Yatli, 

Thank you for delivering this awesome GUI app. It's my 3rd day using it - it feels absolutely slick. 

My question is **how to yank strings from system clipboard to Fvim**? I've attempted <C-v>; Win-V; middle mouse button etc; where I could see these key strokes correctly typed inside FVim, but not the intended strings.

I'm on Windows and my clipboard is set to 
     set.clipboard = "unnamedplus"

Nvim 0.8 dev and all plugins are latest

**Comment by doychi** [comment]
Have you tried from within fvim:

copy:  "+y<motion>
paste: "+p

**Comment by DanWiseProgramming** [comment]
This does not work for me either with WSLv2. `:checkhealth` reports `FVimClipboard` as the clipboard tool installed, however setting/un-setting the clipboard in nvim's configuration to `unnamedplus` has no effect and the `"` register does not contain content copied from Windows. Upon initial startup, `nvim` even thinks that there is no clipboard tool installed (it presents an error whenever I attempt to paste with `p`) until I run `:checkhealth`, after which it stops complaining.

**Comment by yatli** [comment]
https://github.com/neovim/neovim/issues/13331

If you're seeing the misbehavior, it means my workaround has failed. Need to find something new again :)
