### ISSUE TITLE
Images of telescope-media-files are displayed in the terminal.

### ISSUE THREAD

**Issue by Eloitor** [yatli/fvim#234]
Steps to reproduce:
Install https://github.com/nvim-telescope/telescope-media-files.nvim
Run `fvim` from a terminal.
When previwing an image, the preview is displayed in the terminal and not in fvim.

**Comment by yatli** [comment]
That's one of a novel bug 🆕 

I feel this is a plugin bug that assumes that neovim is ran in a sixel-enabled environment and then forced the sequence onto stdout.

**Comment by Eloitor** [comment]
Thank you, I'll open an Issue there

**Comment by yatli** [comment]
A fellow frontend dev kindly pointed out that the plugin is not using sixel but some magical X11 window overlays. So correction:

> I feel this is a plugin bug that assumes that neovim is ran in a ____ environment and then forced the sequence onto ____.

Replace sixel with X11 magic :)

**Comment by yatli** [comment]
closing for now, feel free to update.
