### ISSUE TITLE
create .app on apple silicon (m1)

### ISSUE THREAD

**Issue by luxus** [yatli/fvim#236]
Hi, I tried your app and found out that it's intel binary :(
Building the app myself was not a problem, but how do i get it into /Applications/ in a FVim.app ?

**Comment by yatli** [comment]
`pack.sh osx.11.0-arm64`

**Comment by luxus** [comment]
hi yatli,
Thanks for the fast response,
what i did was downloading the release and copied it to /Applications
Download and install https://dotnet.microsoft.com/en-us/download
````sh
git clone https://github.com/yatli/fvim
cd fvim
dotnet build -c Release
./pack.sh osx.11.0-arm64
cp -R bin/Release/net6.0/osx.11.0-arm64/* /Applications/FVim.app/Contents/MacOS/
````
Is it possible to have a build included in releases for the next release?

**Comment by yatli** [comment]
`pack.sh` should generate a zipped app package under publish folder already, but yeah copying the files would also work.

**Comment by luxus** [comment]
i created a pull request.. i hope i did it right :D

**Comment by yatli** [comment]
ooh, I didn't realize `pack.sh` does not work for arm64. Good catch!

Could you verify that it will generate zipped app that is actually working? If so I'll add it to the release pipeline.

**Comment by luxus** [comment]
yes it works

**Comment by yatli** [comment]
great, let's merge this.

**Comment by yatli** [comment]
https://v-yadli.visualstudio.com/fvim/_build/results?buildId=730&view=artifacts&pathAsName=false&type=publishedArtifacts

CI pipeline is now generating osx-arm64 artifacts.

Thanks!

**Comment by luxus** [comment]
thank you so much 

ps its just cosmetics but its macOS instead since many years and its aarch64 instead of arm64

**Comment by yatli** [comment]
first part (s/OSX/macOS) I fully agree. Too old to notice the world has moved on (and I even expect to see suffix like -ppc :O ).

For arm64 vs aarch64, I'm not sure though. Debian says arm64 but Fedora/Arch says aarch64. It depends on the macOS convention (if there is one).

**Comment by luxus** [comment]
i guess debian and you are similar "Too old to notice the world has moved on" j/k :D
nix use aarch64 too.. i think debian is the only one :D
