### ISSUE TITLE
fvim stuck when hit tab auto-completion

### ISSUE THREAD

**Issue by zjiekai** [yatli/fvim#249]
When I typed `:ed ~/[tab]`, fvim would stuck sometimes.

In the gif, the first time I pressed tab fvim is fine, but the second time fvim stuck.

![fvim](https://user-images.githubusercontent.com/1871071/230820100-e389d332-80e8-409e-8213-ed8284541347.gif)

**Comment by yatli** [comment]
Can confirm, thanks for reporting.
Newer nvim is using GUI popup menu for command line, and fvim is not yet ready for this.

**Comment by yatli** [comment]
fixed in https://github.com/yatli/fvim/commit/ba6d6286576c1e72ebc70981803dca388207b584
