### ISSUE TITLE
Issues with keymaps on macOS

### ISSUE THREAD

**Issue by TylerLeonhardt** [yatli/fvim#25]
Steps to reproduce:

1. Insert mode
1. type “backtick” (\`) char, equals ` = ` char, tilda ` ~ ` char or plus ` + ` char

Expected:

backtick, equals, tilda, or plus is written

Actual:

“none” is written for backtick and equals
nothing is written for tilda and plus

![image](https://user-images.githubusercontent.com/2644648/60684568-45152a80-9e53-11e9-8440-c6f8e2064992.png)

NOTE:

on my keyboard layout (standard en-US), tilda is accessed via <kbd>SHIFT</kbd>+<kbd>`</kbd> and plus is accessed via <kbd>SHIFT</kbd>+<kbd>+</kbd>

**Comment by yatli** [comment]
This is an upstream issue, see: https://github.com/AvaloniaUI/Avalonia/blob/master/native/Avalonia.Native/src/OSX/KeyTransform.mm#L29

Some of the keycodes are commented out.

**Comment by yatli** [comment]
CC @kekekeks @jkoritzinsky

**Comment by yatli** [comment]
upstream PR merged.
