### ISSUE TITLE
Improve startup speed on macOS

### ISSUE THREAD

**Issue by linrongbin16** [yatli/fvim#251]
Hi, it takes 10+ seconds to startup fvim on macOS. Is it a .NET limitation ? Terminal only use 30ms.

**Comment by yatli** [comment]
not sure what is happening. anything interesting from the logs?

**Comment by marcelkorpel** [comment]
What kind of CPU do you have, @linrongbin16? Mine is an M1, where I presume Rosetta2 kicks in before actually starting the application.

**Comment by linrongbin16** [comment]
mac M1 MAX silicon chip
