### ISSUE TITLE
FVim --setup registers wrong pattern in file association

### ISSUE THREAD

**Issue by monologconnor** [yatli/fvim#253]
Hi, I just installed fvim today and attempted to register file association under `Windows 11` via `Fvim.exe --setup` command.

After running the command I found the **broken** fvim command line shown in `Open With` while opening the `.txt` file, which is shown as `D:\Sync\Program\Fvim\FVim.exe" ""%1"`, which is actually not usable since nothing showed up after select on that.

![图片](https://github.com/yatli/fvim/assets/38450642/732c7b9f-3a2c-48bd-9436-bb8a4907c23c)

I think that's the issue from the register table and I found that all `command` registry item for fvim is written incomplete with a missing quote mark `"`, for example, under the registry path `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\FVim.txt\shell\edit\command`

![图片](https://github.com/yatli/fvim/assets/38450642/4059bd53-52e0-496e-b5e4-7d3295dd4358)

I tried to manually edit this item by finishing the quote pair: `"D:\Sync\Program\Fvim\FVim.exe" ""%1"` and the Fvim now could be invoked correctly.

I checked through the latest source code of Fvim and I found the problem might be caused by this line: https://github.com/yatli/fvim/blob/2d9ea840b3ae7e1d9db17b73c7ad42c28bccd22e/shell.fs#LL84C1-L84C53

`command.SetValue("", $"{exe}\" \"%%1\"")` should be changed to `command.SetValue("", $"\"{exe}\" \"%%1\"")`.

I'm new in making PR and never tried building this project, I'm afraid of making something wrong in source code, can someone fix this issue in source code?

Thanks!

**Comment by monologconnor** [comment]
just found this issue is related to https://github.com/yatli/fvim/pull/231

**Comment by yatli** [comment]
Hey @monologconnor,

Thanks for spotting and reporting this!
I almost always need multiple shots for this kind of off-by-one mistakes :p

I think it's good now:
![image](https://github.com/yatli/fvim/assets/20684720/c3e93960-4dc1-4d02-b5fd-73578fe71549)

**Comment by monologconnor** [comment]
> Hey @monologconnor,
> 
> Thanks for spotting and reporting this! I almost always need multiple shots for this kind of off-by-one mistakes :p
> 
> I think it's good now: ![image](https://user-images.githubusercontent.com/20684720/237648178-c3e93960-4dc1-4d02-b5fd-73578fe71549.png)

Great! Thanks!
