### ISSUE TITLE
fvim titlebar does not respect windows color scheme

### ISSUE THREAD

**Issue by joukevandermaas** [yatli/fvim#255]
I'm on windows 11. My computer is set to dark mode, but the fvim title bar is still using the light color scheme. It also does not use the theme color like other windows do. This makes it hard for me to see if the window has focus.

**Comment by joukevandermaas** [comment]
I'm not really sure what to do in that case. My color scheme is also dark, but the title bar is bright white. Personally I would prefer it just follows my system preferences since every other app I use also follows them.

If that's not something you would want for the project then feel free to close this issue.

**Comment by yatli** [comment]
`FVimCustomTitleBar v:true             " themed with colorscheme`

^ try this?

**Comment by joukevandermaas** [comment]
Thanks, that is better. It has some disadvantages but I can live with those. I'll close this issue now, because this solution is good enough for me.
