### ISSUE TITLE
Blank window on neovim 0.92

### ISSUE THREAD

**Issue by meluskyc** [yatli/fvim#263]
[neovim 0.92](https://github.com/neovim/neovim/releases/tag/v0.9.2) had some changes that break the fvim UI. 

`grid_line` now passes a `wrap` boolean. I'm guessing this is only useful for the TUI since I don't see neovide or other GUIs handling this yet. Unfortunately, this breaks pattern matching of the event. https://github.com/neovim/neovim/commit/981acc2922ce9a5f214ba14acbb1e444748855f2

`grid_line` can also send a cell with a repeat count of zero now. I don't think fvim does anything when `cell.repeat` is zero, so I'm not sure any changes are required for this.

**Comment by jeremy-coleman** [comment]
blank screen for me too

**Comment by lost22git** [comment]
same problem

**Comment by kceiw** [comment]
Same problem here too.

**Comment by anosatsuk124** [comment]
Same problem

**Comment by yatli** [comment]
Should be fixed with #264
