### ISSUE TITLE
Open fvim , can't see anything 

### ISSUE THREAD

**Issue by jiangyz7cc** [yatli/fvim#267]
I stopped all extensions , switch the theme to default , still like this:
![图片](https://github.com/yatli/fvim/assets/19501269/18ecff65-efe3-4afc-9324-929306648b49)

It looks all the content is the same color
I tried to change the theme to white one: shine , then it became an all white window.

Environment:
Windows 11
NeoVim 0.10.0
fvim 0.3.548

**Comment by yatli** [comment]
See #263

**Comment by jiangyz7cc** [comment]
> See #263

Thanks laoge , the new version now works.
