### ISSUE TITLE
Add icon to FVim on macOS

### ISSUE THREAD

**Issue by TylerLeonhardt** [yatli/fvim#27]
It would be nice if the icon showed up here:

![image](https://user-images.githubusercontent.com/2644648/60685059-f4530100-9e55-11e9-9fa7-c4722e47403a.png)

**Comment by TylerLeonhardt** [comment]
blocked on Avalonia - https://github.com/AvaloniaUI/Avalonia/issues/2649

**Comment by yatli** [comment]
How about this:

![image](https://user-images.githubusercontent.com/20684720/61707333-d0ac1800-ad7c-11e9-8efd-9f7d797d2dac.png)

:D

**Comment by yatli** [comment]
well I still envy this:

![image](https://user-images.githubusercontent.com/20684720/61707582-68116b00-ad7d-11e9-8cb7-40945af67481.png)

**Comment by yatli** [comment]
Looks like I've got it working.

![image](https://user-images.githubusercontent.com/20684720/61723617-0530cb80-ad9f-11e9-96e5-3a8cb7da3110.png)

Also, note the black corners are gone -- nothing's changed in the code, probably it's fixed by the appbundle...
