### ISSUE TITLE
Consider moving to a single file executable?

### ISSUE THREAD

**Issue by TylerLeonhardt** [yatli/fvim#28]
Since .NET Core 3.0 supports it:
https://dotnetcoretutorials.com/2019/06/20/publishing-a-single-exe-file-in-net-core-3-0/

**Comment by yatli** [comment]
Actually I tried that -- all it does is to pack everything into an archive, and upon first run, extract it in a temporary directory.

Best security practice (tm).

**Comment by yatli** [comment]
Let me close this one for now; We can keep this idea revisited when the situation improves.
If a real single-exe assembly with proper stripping is possible, we will get a very small executable file that is fast to load.
