### ISSUE TITLE
Not working in linux

### ISSUE THREAD

**Issue by codehz** [yatli/fvim#3]
version: latest release(0.1.53)
environment:
wm: i3wm
disto: Archlinux

![image](https://user-images.githubusercontent.com/13158903/57535189-4c004f00-7374-11e9-952a-b20bbef4ccd5.png)

**Comment by yatli** [comment]
Hey codehz,

Thanks for checking out. I noticed this problem. It stopped working when I migrate to offline rendering. Fixing it now;

**Comment by yatli** [comment]
looks like it's a SkiaSharp-related problem.

**Comment by yatli** [comment]
the latest release (v0.1.66) fixes this issue
