### ISSUE TITLE
drag'n'drop

### ISSUE THREAD

**Issue by yatli** [yatli/fvim#34]

**Comment by yatli** [comment]
update: awaiting upstream changes.

**Comment by Teeheey** [comment]
Hi)
First of all thank you for your work, after few weeks of choosing betwen Nvim UI clients i have stopped with FVIM.
Just want to know, do you want to implement drag'n'drop feature? i mean drag file via mouse and put in fvim window.

**Comment by yatli** [comment]
@Teeheey it's done, at last :)
