### ISSUE TITLE
Colemak layout

### ISSUE THREAD

**Issue by bfulop** [yatli/fvim#40]
Hello,

I've set my US keyboard to use a Colemak layout in macOS. I'm noticing that fvim still inputs characters as if I was on the default layout.

I saw that in the readme you mentioned that the [input method support](https://github.com/yatli/fvim#goals) is still a work in progress. 

So this means that for now Colemak is not yet supported or is there a way to activate support for it?

And thanks for this great software, I was testing it briefly and the text rendering looks great! I'm looking forward using fvim more in the future!

**Comment by bfulop** [comment]
As a **temporary** solution, if others are having the same issue, I've set Karabiner Elements to remap the keys and it lets me write Colemak with fvim.

**Comment by yatli** [comment]
Hi!

This is a known issue -- see #36 -- the UI framework is sending wrong key codes.
I will work with the Avalonia friends to solve this. Until then, I guess you'll have to do keyboard remapping.

**Comment by yatli** [comment]
The strange thing is, on Windows, dvorak works fine for me

**Comment by bfulop** [comment]
Thanks @yatli! Luckily the key remapping works well, so I can use FVim ! So far the experience is really great!

**Comment by yatli** [comment]
Great! I'm glad it works for you.
Feel free to post suggestions / if you encounter any problems.
Closing this now, tracking it at #36.
