### ISSUE TITLE
Set line-height

### ISSUE THREAD

**Issue by bfulop** [yatli/fvim#42]
Hello,

Is there a way to configure the line-height used by Fvim? Ideally I would like to increase it a bit...

**Comment by yatli** [comment]
Do you want to increase the extra padding after each line?

**Comment by yatli** [comment]
I think this is a nice-to-have feature, would be handy for font-tweaking.

**Comment by bfulop** [comment]
Great, thanks @yatli! 

Yes, I was referring to the CSS property `line-height`, but it's probably achieved via adding padding between the lines ([leading](https://www.figma.com/blog/line-height-changes/)) as you wrote! :)

**Comment by yatli** [comment]
implemented.
usage:
`:FVimFontLineHeight "height"`

`"height"` must be a string, and can be of these forms:
- number: "16.0" -- absolute
- signed number: "+1.0" "-1.0" -- additive
- "default" -- same as "+0.0"

**Comment by yatli** [comment]
@bfulop pushing out a new release. I'm quite happy with the result -- I can manually "compact" the font rendering now :)

**Comment by bfulop** [comment]
Hello @yatli, thank you so much for this quick update, it was really fast! 👍 

It looks great on my system (macOS), especially using an absolute number. With the "signed number" option, I do see the change in line-height but somehow now as granular. Going from "+1.0" to "+3.0", I don't see a noticeable difference. I may have to play around with a bit more.
