### ISSUE TITLE
Running multiple instances, launching from command line (macOS)

### ISSUE THREAD

**Issue by bfulop** [yatli/fvim#44]
Hello,

So far I was just launching the app by double-clicking the FVim.app that came with the dmg release. I was wondering if I could have several fvim processes with different projects (root workspace folders) in them? 

Is there way to launch multiple instances of fvim and/or launch it from the command line? The [launch options](https://github.com/yatli/fvim#startup-options) from readme give me some hint that it's possible.

**Comment by yatli** [comment]
hmm. On Windows this is simple -- shift-click the app icon will open another instance.
On MacOS -- I guess there's something similar? Maybe there's some kind of flag to support this in Info.plist.

The command line executable is located at FVim.app/Contents/macOS/FVim -- try execute that from the shell.

**Comment by bfulop** [comment]
Thanks, it does work indeed! I can `cd` to `FVim.app/Contents/macOS/FVim` and run `./FVim` and have multiple instances of Fvim !

I guess the command line options should work as well with this method?

**Comment by yatli** [comment]
yes, exactly.
btw, you can add that to your PATH (in your .bash_profile, for example):
`export PATH=/Applications/FVim.app/Contents/macOS:$PATH`

**Comment by bfulop** [comment]
Nice, thanks @yatli, works great with the `PATH` update!
