### ISSUE TITLE
shift key not working correctly in linux

### ISSUE THREAD

**Issue by codehz** [yatli/fvim#48]
Version: v0.2-56-gfd39a12
Environment: X11 (gnome 3, Archlinux, install via debtap)
cannot input `~!@#$%^&*()_{}|:"<>?` (both normal mode and insert mode)
but the `+` and alphabet keys are working

**Comment by yatli** [comment]
hi! what's your keyboard mapping?

**Comment by yatli** [comment]
I'll see if I can repro this on WSL Arch.

**Comment by thautwarm** [comment]
can confirm.

**Comment by yatli** [comment]
can also confirm on WSL.
Weird, it was working before...

**Comment by yatli** [comment]
Until then, activating the workaround.

**Comment by yatli** [comment]
waiting upstream: https://github.com/AvaloniaUI/Avalonia/pull/2883

**Comment by yatli** [comment]
upstream merged.
waiting for the new ci build.

**Comment by yatli** [comment]
upstream ci build is released.
updating our ci build -- @codehz @thautwarm @jjohnson338 please test it out

**Comment by yatli** [comment]
also gives a hint on #36 -- it probably can be solved in a similar way

**Comment by yatli** [comment]
> So it seems as if it's interpreting the following keys were entered in order
> c,a,p,s,l,o,c,k

LOL
noted, will fix this!

**Comment by yatli** [comment]
I also remap `capslock` to `esc` -- on Windows this is done via a registry hack, and it works pretty well -- so I never really tried to input `capslock`! :D

**Comment by yatli** [comment]
@jjohnson338 please try `v0.2-68-gb2d9574`.

**Comment by yatli** [comment]
@jjohnson338 glad it works for you :)
closing this issue now;
