### ISSUE TITLE
FVimToggleFullScreen not untoggling on Linux

### ISSUE THREAD

**Issue by jjohnson338** [yatli/fvim#50]
OS: Arch Linux
Desktop: Budgie

The `:FVimToggleFullScreen` command works when toggling into fullscreen, but attempting to toggle out of full screen appears to do nothing.

**Comment by yatli** [comment]
uh oh.. so we have to figure out an alternative escape hatch :)

**Comment by yatli** [comment]
@jjohnson338 there might be a silent exception that prevented the exit sequence.
could you try to enable logging and upload the captured logs?

logging can be enabled with `--trace-to-file`, the file will be created in `~/.config/fvim`

**Comment by jjohnson338** [comment]
Hi @yatli, I've updated to the latest release and captured the trace as you asked. The only actions I took in the trace were as follows:
1) Launch `fvim`
2) Toggle Fullscreen On
3) Toggle Fullscreen Off
4) Quit


[Log Capture](https://gist.github.com/jjohnson338/9dd642609b2252c8180427c2cc9c06da.js")

**Comment by yatli** [comment]
after the first `ToggleFullscreen`, the buffer size changes correctly, but nothing happened after the second.

Could you please try alt-drag the (failed) untoggled window down a little bit and see if the title bar is restored?
My guess is that title bar is restored correctly, but the window position information is lost, so it got stuck at (0,0)

**Comment by jjohnson338** [comment]
@yatli , I tried both dragging the window around and using some set keybinds to maximize/un-maximize the window, no action seemed to have any affect. `fvim` still appeared to be in it's full-screen mode.

**Comment by yatli** [comment]
do you mean that when you drag the window, you still don't see the title bar, or it simply didn't move around?

**Comment by jjohnson338** [comment]
@yatli When I alt+drag the FVim window following toggling off FullScreen, I don't see the titlebar and the window doesn't move. There is no visual change.

**Comment by yatli** [comment]
does alt+drag move other windows in your desktop environment?

**Comment by jjohnson338** [comment]
Yes. I needed to set it up, but I have confirmed that works as expected for other applications. It appears to me as if `fvim` never leaves FullScreen mode. I haven't tried with other desktop environments, so it could potentially be some isolated conflict with `Budgie` itself?

**Comment by yatli** [comment]
@thautwarm could you please help to test this out?
If it does not work, I'll set up a VM and fix it there.

**Comment by jjohnson338** [comment]
@yatli  I just tested this feature on Fedora 29 which is bundled with Gnome 3 by default (which Budgie is build from). The fullscreen toggle worked there. So I'm more confident now saying it's a issue only on `Budgie`

**Comment by yatli** [comment]
yeah, from my (outdated) understanding of linux DE, anything not fixed to the root window can be alt-dragged, include a fullscreen-ed window. some terminal emulators even automatically resume the title bar when being alt-dragged.

so if something is stuck and refuse to be moved around, it must be stuck in a special state (e.g. fixed to the root window)

**Comment by yatli** [comment]
@jjohnson338 does this work for you: https://github.com/lambdalisue/vim-fullscreen

**Comment by jjohnson338** [comment]
@yatli I installed both the plugin and `wmctrl`. Fullscreen toggling via that plugin works fine on my machine.

**Comment by yatli** [comment]
I've finally set up a Fedora VM for testing.. Will install Budgie and try it out.

**Comment by yatli** [comment]
@jjohnson338 Fedora30+Budgie works well on my side.

**Comment by jjohnson338** [comment]
@yatli Thanks for testing. Can confirm with the latest release I'm still running into this issue. I did spin up `neovim-qt` and ran what should be their synonymous function:
```
call rpcnotify(0, 'Gui', 'WindowFullScreen', 1)
call rpcnotify(0, 'Gui', 'WindowFullScreen', 0)
```
Fullscreen toggles correctly there. Not sure what is special (or cursed 😜) about my setup.

**Comment by thautwarm** [comment]
@yatli Sorry for the late reply. I'm at a ddl now and will check this by 22. Currently my internet fails at `dotnet build -c Release`...

**Comment by yatli** [comment]
No worry. Take your time!

**Comment by yatli** [comment]
@jjohnson338 if you feel like digging into this problem, you can use `VSCode` to set a breakpoint at `EditorViewModel.fs`, around line 73, function `toggleFullScreen`

**Comment by jjohnson338** [comment]
@yatli I'll attempt to debug it this weekend. Thanks for the tip!

**Comment by jjohnson338** [comment]
@yatli  Just letting you know I haven't forgotten about this. I need to borrow an adapter from friend so I can hookup an external monitor to debug. Will report back when I have findings or a fix.

**Comment by yatli** [comment]
As of v0.2.306 this seems to be fixed? @jjohnson338
