### ISSUE TITLE
Initial Window Size is Tiny on Linux

### ISSUE THREAD

**Issue by jjohnson338** [yatli/fvim#51]
![image](https://user-images.githubusercontent.com/1017310/63820875-f054d400-c918-11e9-917b-c5d29ecee376.png)

**Comment by yatli** [comment]
does it remember the last window state? I might accidentally broke this feature.
also, check ~/.config/fvim, it will keep track of window positions based on working directory

**Comment by zgpio** [comment]
> does it remember the last window state? I might accidentally broke this feature.

我是在macos上测试的（没有加载配置），它没有记住上次窗口的状态，而且，初始窗口很小。

**Comment by yatli** [comment]
a patch is pushed. please reopen if it does not fix the problem.

**Comment by bfulop** [comment]
I had the same issue on macOS and this patch resolved it for me as well! 
Thanks yatli!
