### ISSUE TITLE
Pressing "super" key causes "none" to be entered

### ISSUE THREAD

**Issue by beelzebielsk** [yatli/fvim#57]
OS: Arch Linux
window manager: i3

Whenever I press the "super" key (often bound to the windows key on a keyboard), fvim treats it as if I pressed the keys "n" "o" "n" "e", in that order. An example of this behavior, if I press the super key while in normal mode in an empty buffer, the buffer will look like
```

ne
```
Because the "n" will have no effect, the "o" will start insert mode on the next line, and then "ne" will be pressed while in insert mode.

This makes fvim unusable for me, since the "super" key is part of how I use i3.

I apologize if there is a specific format an issue should follow, I couldn't find anything like that in your readme/documentation. Lemme know if you need me to add things.

**Comment by yatli** [comment]
Hey @beelzebielsk , thanks for reporting. Don't mind the issue formatting now, because I think that's for a larger project with a more complex triage process.
This problem sounds familiar -- will look into this shortly.

**Comment by yatli** [comment]
no repro on Windows or OSX.
setting up a Fedora VM to test this

**Comment by yatli** [comment]
Test drive on Fedora30:

- GNOME 3, with left super key unmapped: repro
- i3, with super key as mod: repro

Both `LSuper` and `RSuper` trigger "none".
This is an upstream issue. I'll work with the Avalonia friends to fix it.

**Comment by yatli** [comment]
awaiting upstream changes.

**Comment by beelzebielsk** [comment]
Tested, fix worked. I don't see any of this behavior when I press the super key.
