### ISSUE TITLE
Black screen / spinning beachball with the latest release

### ISSUE THREAD

**Issue by bfulop** [yatli/fvim#58]
Hello,

I've just downloaded the latest release of FVim (v0.2-96-g269872a) for the macOS.

When I start it up, the whole application window remains black, it goes into "beachball mode" (unresponsive application) and need to force quit it.

I usually download new releases of Fvim and never had any stability issues with it so far.

<img width="1211" alt="Screenshot 2019-09-09 at 11 40 43" src="https://user-images.githubusercontent.com/1718128/64520561-b6aba200-d2f6-11e9-9c69-60595c3a4e5f.png">

**Comment by bfulop** [comment]
UPDATE: it looks like the release v0.2-88-g17b59dd: Merge pull request #53 from yatli/popupmenu also has the same startup bug.

I've tried v0.2-71-g5bc3070 and it opens up correctly on my machine. I will test a bit more later when I'll have more time...

**Comment by yatli** [comment]
@bfulop please try start fvim with `--trace-to-file`, and attach ~/.config/fvim/fvim_timestamped.txt

Blind guessing two causes:
1. upgraded Avalonia nightly build
2. please check `nvim --version`, I guess I haven't tested enough with `<0.4.x`

**Comment by bfulop** [comment]
Thanks, @yatli, I downloaded version `v0.2-96-g269872a` and started it with the `--trace-to-file` flag. Here's the generated log file:

https://send.firefox.com/download/deedfc438ec04be2/#n-MFivuABIwZxAKOoQ40Tw 

And my nvim version (not the very latest, but on the `.4.x` branch):

```bash
NVIM v0.4.0-2471-g66149ecff
Build type: Release
LuaJIT 2.0.5
```

**Comment by bfulop** [comment]
I tried running Fvim (latest version, at `v0.2-96-g269872a`) with a blank `init.vim` and it runs without any issues!

So it's related to my `init.vim` file. I will try to debug it. Could be related to a custom line-height setting. I will start by removing the fvim related settings.

**Comment by bfulop** [comment]
I haven't but found the cause of the bug, but first removing everything around

```init.vim
if exist('g:fvim_loaded')
...
endif
```

then restarting Fvim (starts up correctly), then restoring this block to the _exact same state as before_, now solved this issue, Fvim now runs correctly.

So probably it was related to some old build, or cached config.

I close this issue now.

**Comment by bfulop** [comment]
Unfortunately I have to reopen the issue. The startup is now OK, but now I'm getting random crashes. 

For example running `:PlugUpdate` and just when the Plug update split would close, Fvim freezes ("spinning beachball"). -> [trace file](https://send.firefox.com/download/db65a20da077f3cb/#sjwYOJlpljs_KUKHzKKPLQ)

Or sometimes just doing `:bd` would make the app unresponsive (but not always). -> [trace file](https://send.firefox.com/download/3ce9e690de2d187c/#utO3MaCMNQyi6cDCeMxHHQ)

Or just now, opening the trace file can cause this issue. -> [trace file](https://send.firefox.com/download/f226468fb85aa241/#-7pgFHY-sesClpOUmpEw6g)

**Comment by yatli** [comment]
the log files look fine to me -- all seems suddenly cut off though.
any `fvim-crash-timestamp.txt`?

**Comment by bfulop** [comment]
The ones I see are all from two days ago (when I first reported the issue), but none from today.

Here's a [few in a zip file](https://send.firefox.com/download/f313ccab485c3cd1/#wBQ_eMixptwgqg6IvJPq3g)

**Comment by yatli** [comment]
I've checked the log files. All of them report a broken pipe, which means the embedded `nvim` process has exited unexpectedly. Does `nvim` work in a terminal? Also, check the system Console app -- there's got to be crash logs for `nvim`

**Comment by bfulop** [comment]
Thanks, I will check these logs. 

What's strange that I don't have these crashes with previous versions of Fvim or other Neovim clients (terminal or VimR). 

I will start by updating my Neovim installation then check the data available from the console app.

**Comment by bfulop** [comment]
I've downloaded the latest version of Neovim, but unfortunately didn't solve this issue.

Also tried to check the system console logs, but since Fvim just freezes, I have the impression that it doesn't write out any crash logs. The only ones I could find, were older logs, that I think are unrelated to this issue.

I've tested again the different Fvim releases, and version `v0.2-71-g5bc3070` is still stable on my machine. From then on, it looks like quick updates to the buffer (scrolling, `:PlugUpdate`) will sooner or later freeze the app.

One thing to add: I have a very slow machine (2015 MacBook 12"), maybe it's related to this? I will receive a new Mac in about a month, and will be able to test if a faster, new machine changes anything.

**Comment by yatli** [comment]
thanks for testing! I'll check the changes and see if there's anything suspicious around `g5bc3070`.

**Comment by yatli** [comment]
I have reproduced the problem in a VM. Looking into it.

**Comment by yatli** [comment]
ok the root cause is that one of my optimization tricks causes a dead lock on osx.
I have disabled that one for osx for now.
@bfulop I'll push out a new release shortly. Please reopen if it still doesn't work for you. Thanks!

**Comment by bfulop** [comment]
Thank you so much @yatli!

I've testing the latest release and can confirm that the issue has been resolved!
