### ISSUE TITLE
Long start up --wsl 

### ISSUE THREAD

**Issue by nree** [yatli/fvim#59]
Great project, enjoy it a lot.

I get very long start ups, around 1-2 minutes when:
- first launch after Win10 boots (or reboots), Reproduce 100%; always happens
- after first launch, closing and opening is very fast, But still sometimes it still will take 1-2 minutes to launch again this is not common. Can't reproduce 100%.

When I first downloaded fvim, I thought it didn't work because it doesn't open... I realized I just need to wait.

~~Without `--wsl` it always starts fast.~~ It seems to have the same issue without --wsl.
Don't know how to debug further.

System: 
Win 10 x64 
WSL 1, ubuntu disco
neovim 0.3.4 (official package from disco repo)

**Comment by yatli** [comment]
wild guess: `Windows Defender`

**Comment by yatli** [comment]
try run fvim with `--trace-to-file` and post the log file.
you can find the file under `%LocalAppData%/fvim/`

**Comment by yatli** [comment]
Weird, all my win10 boxes have defender enabled but I don't see this happening.
Are you on a corporate network (i.e. with a domain controller)?
I do have seen something like this before with some `msys2` programs.
Some abracadabra happens between the program, some syscall, the filter driver, AV and the domain controller, asking for identity verification that comes back ~2mins later for a single command.

**Comment by nree** [comment]
> Weird, all my win10 boxes have defender enabled but I don't see this happening.

Weird indeed, I don't see this happening anymore for me either.

Sorry for not testing more sooner, now my setup has changed:
- was using release version of fvim (not sure which version, maybe v0.2-88-g17b59dd? not sure ). Now I have switch to build from master.
- I updated neovim in my WSL 0.3.4 -> 0.3.8 

I will try to go back to older neovim later and test again. If can't see, maybe assume either already fixed in master or something weird with my setup before.

**Comment by nree** [comment]
Closing, can't reproduce anymore...

Tried to revert back to previous conditions but still can't reproduce.
