### ISSUE TITLE
Issues rendering italic and underlines

### ISSUE THREAD

**Issue by nree** [yatli/fvim#60]
![Untitled](https://user-images.githubusercontent.com/12157634/64655381-1a6ac380-d3fa-11e9-8bdb-005e9dcdffb7.png)

Sorry for poor job on the pic but:
Top line is fvim
Bottom line is cmder / conemu running vim (nvim)

This is Windows 10, using same font (SF Mono), same vim config, same wsl / neovim. 

- Cuts off italic last letter
- Cuts off italic height of some letters (g in settings)
- Underlines swiggles aren't connected, has a dotted look to them and look poor quality

I tried different fonts:
- Consolas: italics ok has minor clipping except for underlines
- Source Code Pro: italics slightly clips but not bad at all, underlines still bad
- Fira Code: very bad clipping on italics and underline

I've tested fonts on other apps: Cmder (conemu) in the picture, tested with visual studio code, and emacs.

**Comment by yatli** [comment]
interesting. looks like the font measurement function calcs off.
for height, you can workaround this by setting :FVimFontLineHeight (for example, `:FVimFontLineHeight '+1.0'`)

**Comment by yatli** [comment]
The horizontal clipping is weird. `fvim` conducts backward rendering so if the line comes in, later glyphs will be drawn first.

**Comment by yatli** [comment]
The horizontal clipping is repro'ed and I think I've pinpointed the issue:

https://github.com/yatli/fvim/blob/4e77a9b93630d9b4714c532a9308b844e7a5686d/ui.fs#L344

**Comment by yatli** [comment]
@nree I'll push out a release soon. it should be fixed

**Comment by nree** [comment]
Looks very very good now! Some of them best I've seen 😁

Regarding line height issue: (italic g, y + underline) I noticed something new... I need line height +1.5 for my use to get clear height.

But if I do line height +1.0 it actually renders good after setting line height (first render). But then on re-renders after it will clip. Is this a bug? So it seems possible to render these height issues good, just something in the render clips them after. Should I open new issue about this?
