### ISSUE TITLE
Possible weird state where :Explore freezes fvim

### ISSUE THREAD

**Issue by nree** [yatli/fvim#62]
`:Explore` working fine on fvim Windows 10 --wsl. Then one day `:Ex` will freeze every time. Restart fvim or Windows 10 doesn't fix. But CtrlP or `:e` work fine.

I figured out how to reproduce. It has something to do with conflicting default? dirs for neovim. 

1. Open neovim in WSL `$ nvim` in a terminal (no need to do anything after)
2. Create a Windows shortcut for fvim with --wsl (target Fvim.exe --wsl, Start in: empty) this should make default dir the Windows desktop dir or wherever you created shortcut)
3. Start fvim through shortcut, Do `:Ex` in fvim

Now it freezes, fvim will be in a bad state where it freezes everytime you `:Ex` no matter what dir you pick.

To fix, have to 'sync' with WSL neovim backend.
1. neovim in WSL do `:Ex <pick a dir>`
2. fvim do `:Ex <same dir as above>` 

Now everything works again. For me I can reproduce with these steps every time. Think it has something to do with fvim getting stuck on path translation once it sees an error (C:\ instead of /mnt/c).

Once you fix, the shortcut created no longer causes issues. Have to re-create a new shortcut to force the problem again and re-do all steps exactly.

**Comment by yatli** [comment]
@nree please let me know if it works for you -- feel free to reopen if it doesn't!

**Comment by nree** [comment]
Yes confirmed!
