### ISSUE TITLE
Airline colors wrong

### ISSUE THREAD

**Issue by Kethku** [yatli/fvim#63]
In nvim and nvim-qt I get perfectly fine airline colors, but in fvim I cannot.

![image](https://user-images.githubusercontent.com/3323631/64823605-b4eb1400-d56c-11e9-8d31-8747294a37d4.png)

Pictured is my init.vim configuration and the issue. Repeated below is my config.

if &compatible
  set nocompatible
endif

set runtimepath+=c:/dev/OneDrive/vim/dein/repos/github.com/Shougo/dein.vim

set guifont=Fira\ Code:h13

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('vim-airline/vim-airline')
  call dein#add('vim-airline/vim-airline-themes')
  call dein#add('morhetz/gruvbox')

  call dein#end()
  call dein#save_state()
endif

colorscheme gruvbox

let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_theme='gruvbox'

filetype plugin indent on
set incsearch
set hlsearch
set ignorecase
set smartcase
set clipboard=unnamed

set t_Co=256
let &t_AB="\e[48;5;%dm"
let &t_AF="\e[38;5;%dm"

if exists('g:fvim_loaded')
  FVimFontAntialias v:true
  FVimFontAutohint v:true
  FVimFontSubpixel v:true
  FVimFontLcdRender v:true
  FVimFontHintLevel 'full'
  FVimFontAutoSnap v:true
endif

**Comment by yatli** [comment]
try `:set notermguicolors`

**Comment by Kethku** [comment]
No dice... Any chance you have an example config where airline works in fvim?

**Comment by Kethku** [comment]
Oh ok. Looks like I have to set termguicolors not notermguicolors. I'm not really sure why that works but it does...

**Comment by yatli** [comment]
TBH I don't know the exact reason either, or how nvim-qt works around this.
Anyway, closing this issue now. I'm pasting excerpts from the doc here, in the hope someone could answer the question:

```
'termguicolors' 'tgc'	boolean (default off)
			global
	When on, uses |highlight-guifg| and |highlight-guibg| attributes in
	the terminal (thus using 24-bit color). Requires a ISO-8613-3
	compatible terminal.
```
