### ISSUE TITLE
Linux: glyph under cursor is not synchronizing

### ISSUE THREAD

**Issue by yatli** [yatli/fvim#65]

**Comment by yatli** [comment]
@jjohnson338 have you seen something like this? That is, the cursor always displays a fixed character, not the character in the buffer under it.

**Comment by codehz** [comment]
![image](https://user-images.githubusercontent.com/13158903/65036147-5b745200-d97d-11e9-90ee-3ee85b5508bc.png)

as an example

**Comment by jjohnson338** [comment]
Yes. In my case it seems to always show as a solid block.

![image](https://user-images.githubusercontent.com/1017310/65038225-7dd68300-d91d-11e9-95dd-5d55b4445762.png)

**Comment by yatli** [comment]
I made a stupid error, fixed!

**Comment by jjohnson338** [comment]
@yatli I've pulled master and tested it out. Confirming this issue is fixed on my end :)
