### ISSUE TITLE
feature request: transparent background with blur effect

### ISSUE THREAD

**Issue by TylerLeonhardt** [yatli/fvim#66]
Here's what my terminal looks like:
![image](https://user-images.githubusercontent.com/2644648/64936706-1aa8fb80-d80c-11e9-93ba-13c1582a33be.png)

It'd be really cool to have something similar for fvim

**Comment by yatli** [comment]
awwww I want this

**Comment by yatli** [comment]
related:

https://github.com/riverar/sample-win32-acrylicblur/blob/master/MainWindow.xaml.cs
https://github.com/riverar/sample-win32-acrylicblur
https://github.com/arkenthera/electron-vibrancy/blob/master/src/vibrancy_win.cc

**Comment by TylerLeonhardt** [comment]
oooo

**Comment by yatli** [comment]
glitches all around but here we go:

![image](https://user-images.githubusercontent.com/20684720/65105859-ed756c80-da08-11e9-9bd2-da7f194dc4de.png)

**Comment by yatli** [comment]
well if you feel like a color scheme, acrylic makes it another 10x better:

![image](https://user-images.githubusercontent.com/20684720/65110824-41ce1b80-da0c-11e9-9332-de93b41c301a.png)

totally sold (x

**Comment by TylerLeonhardt** [comment]
Ahhh it looks so goodd

**Comment by TylerLeonhardt** [comment]
I take it this would be Windows only though?

**Comment by yatli** [comment]
I promise to try to bring this to Linux and macOS.

**Comment by yatli** [comment]
Tracking: #74
