### ISSUE TITLE
Linux: Emojis not rendering

### ISSUE THREAD

**Issue by jjohnson338** [yatli/fvim#67]
On Linux, emoji characters are not rendering. I've installed `noto-fonts-emoji` which should be the default emoji font-face and ensured it's recognized 
![image](https://user-images.githubusercontent.com/1017310/65002692-168be500-d8c3-11e9-97c7-d4d6883a15c3.png)

**Comment by jjohnson338** [comment]
Confirmed on Fedora 29 as well.

**Comment by yatli** [comment]
noted, thanks!
will test this out tonight.

**Comment by yatli** [comment]
lol

not that it's not rendering but:

![image](https://user-images.githubusercontent.com/20684720/65051368-971e1480-d99b-11e9-8b35-88f6ac1b561e.png)

**Comment by jjohnson338** [comment]
Oh hahaha. I just saw it as a small dot, didn't think to look that close.

**Comment by yatli** [comment]
I'm looking for a workaround. This is funny.. :D

**Comment by yatli** [comment]
This is probably a Fedora issue? I'll ping the Avalonia guys to see if it rings the bell

**Comment by jjohnson338** [comment]
@yatli This issue is present both on my laptop (Arch Linux) and the Fedora VM I setup for testing, so doesn't seem to be related to just Fedora, but (probably?) Linux as a whole.

I should probably setup an Ubuntu VM as well so I can test these sorts of issues in a third Linux env.

**Comment by yatli** [comment]
According to Avalonia devs, it could be due to Avalonia linked against an older version of fontconfig.
They're glad to know that color font is at least working :D

**Comment by jjohnson338** [comment]
@yatli Thanks for the heads up! Let me know if there is anything I can do to help track down a fix.

**Comment by adelarsq** [comment]
Also occurs on Linux Mint.

**Comment by tssm** [comment]
I don't know if it's the same issue, but I also see smaller emojis (although not that small) on macOS (the bar is the cursor)

<img width="47" alt="Screenshot 2020-03-07 at 19 45 29" src="https://user-images.githubusercontent.com/1188977/76150566-4c5c9a00-60ac-11ea-9eb3-d815c99a6edc.png">

**Comment by MyriaCore** [comment]
Not a fedora issue, I'm on manjaro.

**Comment by yatli** [comment]
As of 0.2.306 this seems to be fixed
