### ISSUE TITLE
Undo --setup

### ISSUE THREAD

**Issue by auxym** [yatli/fvim#68]
Is there a `--uninstall` option?

Not sure why, but ever since I ran `fvim --setup`, on every reboot, fvim pops up with a line saying `net start mavsc`. I'm getting the feeling that fvim associated itself as the default app for `.bat` files, and not they are getting opened in fvim instead at executed at startup?

**Comment by yatli** [comment]
whooops!

see: https://www.winhelponline.com/blog/bat-files-do-not-run-when-double-clicked-fix-association/

**Comment by yatli** [comment]
I'd probably need to revisit the shell documentation and check what's the proper verb for calling an editor.

**Comment by auxym** [comment]
Probably the "edit" verb. Thanks for the link to the reg fixes!

**Comment by yatli** [comment]
@auxym I've added uninstall option. It removes the FVim reg entries, but leaves the HKCR filetype trees intact, because I don't know what values to restore to.

Also updated to "edit" verb. Thanks!

**Comment by yatli** [comment]
Changing to "edit" verb does not fix the interference with .cmd, .ps1, .bat.
Reopening.

**Comment by yatli** [comment]
Update: removed the bad associations...

**Comment by yatli** [comment]
Added heuristics for this..
