### ISSUE TITLE
Lines between powerline characters

### ISSUE THREAD

**Issue by Kethku** [yatli/fvim#72]
![image](https://user-images.githubusercontent.com/3323631/65275306-3ea16100-dada-11e9-8025-7bfd43a18932.png)

Win 10
nvim v0.4.0

Setting:
if exists('g:fvim_loaded')
FVimFontAntialias v:true
FVimFontAutohint v:true
FVimFontSubpixel v:true
FVimFontLcdRender v:true
FVimFontHintLevel 'full'
FVimFontAutoSnap v:true
endif

**Comment by yatli** [comment]
This is a known issue. Try turn off LcdRender (which actually means sub-pixel rendering)?

**Comment by Kethku** [comment]
This fixed the lines on the left hand sides, but they still show up on the right.

![image](https://user-images.githubusercontent.com/3323631/65382682-91883d80-dcbf-11e9-8edb-ca9402c69e78.png)

Maybe this is a problem with my particular font? I'm using fira code v2

**Comment by yatli** [comment]
Possible cause: the font is wider than the powerline glyphs, and the symbols are not properly aligned to the edges.

I also see similar artifacts on various fonts, some better some worse.

**Comment by yatli** [comment]
The line artifacts have background color (strange colors if subpixel), so I'm pretty sure that moving the glyph a little bit will do the trick. But we have to find a universal heuristic to handle left and right.

I already have code to tell if a glyph is a powerline symbol :)

**Comment by yatli** [comment]
Tracking: #103
