### ISSUE TITLE
Running fvim from start menu after fvim --setup doesn't start

### ISSUE THREAD

**Issue by Kethku** [yatli/fvim#73]
Not sure why or how, but running fvim by pressing win key and typing fvim + enter doesn't start up fvim. However when I run it from the terminal it works great.

win 10

**Comment by yatli** [comment]
any logs?

**Comment by Kethku** [comment]
Actually I figured out why this was the case. I set all of my path variables via a powershell profile because I feel I have stronger control over the lifetime and contents of the path variable this way. However this means that when I run install, fvim doesn't know where nvim exists because its not on my system path. I think this could be fixed by making the shortcut pass the location of nvim manually instead of assuming a command called nvim exists.

**Comment by Kethku** [comment]
So I think the ask here is that calling --setup should record the current location of nvim and use that in the shortcut instead of just whatever nvim command is available.

**Comment by yatli** [comment]
understood. thanks for trying out the very experimental stuff -- the setup process needs a lot of improvements! :)

**Comment by yatli** [comment]
Curious, how are you setting up the start menu entry? If it's a manually created shortcut, you can specify `--nvim path-to-nvim`

**Comment by Kethku** [comment]
The start menu entry was auto added by --setup. I did not create it manually. My fix was to add nvim to my global os managed path, but I suspect that shouldn't be necessary if we know where fvim was called from.

**Comment by yatli** [comment]
Should be fixed now..
