### ISSUE TITLE
[Linux] mouse scroll jumps randomly 

### ISSUE THREAD

**Issue by codehz** [yatli/fvim#75]
Similar behavior as vscode (https://github.com/microsoft/vscode/issues/28795)

It is hard to fix it in this side, but I guess we can make a workaround by adding an addition checking for the scroll length... (like ignore scrolling when it too large)

**Comment by yatli** [comment]
noted, thanks! I'll build some guards for this.

**Comment by yatli** [comment]
@codehz Fedora30+KDE5: no repro (?)

**Comment by codehz** [comment]
gnome only(

**Comment by yatli** [comment]
ok, will try a repro again later :)

**Comment by yatli** [comment]
(much much later)
Got a repro, Ubuntu 18.04 + Cinnamon 4.2, so yeah, perhaps anything GNOME-based.

**Comment by Ashymad** [comment]
I can reproduce it with Arch + i3 (no compositor). Installing `imwheel` works as a workaround.

**Comment by yatli** [comment]
Fixed!

```
input: rejected: MouseWheel (None, 30, 19, 0.0, -459.0)
```
