### ISSUE TITLE
Add Powerline Extra Symbols

### ISSUE THREAD

**Issue by pulcinello** [yatli/fvim#8]
With my lightline config:
```viml
let g:lightline.separator = { 'left': "\ue0b8", 'right': "\ue0ba" }
let g:lightline.subseparator = { 'left': "\ue0b9", 'right': "\ue0b9" }
```
You can see some [symbols](https://github.com/ryanoasis/powerline-extra-symbols) don't show as expected.
![Screenshot from 2019-05-18 12 00 59](https://user-images.githubusercontent.com/3975367/57964295-79955b80-7965-11e9-806c-4e8cf1df0edf.png)

**Comment by yatli** [comment]
investigating.

**Comment by yatli** [comment]
@pulcinello the powerline extra symbols are in my lookup table, but I'm not setting a fallback option for it as of yet.

Maybe, force them to render with embedded nerd font?

**Comment by yatli** [comment]
I have tried it out, but I'm not sure about the correct width of these extra symbols.
See:
![image](https://user-images.githubusercontent.com/20684720/57968617-88006900-799f-11e9-8f77-9ac2dcec3a1a.png)
neovim thinks width=1 though.

**Comment by yatli** [comment]
the change is in `master`; please test it yourself :)

**Comment by pulcinello** [comment]
Looks OK. By the way, is there any plan to add an option for fvim-specific settings? Like:
```viml
if exists('g:fvim_running')
  set guifont=Iosevka\ Slab:h16
  call rpcnotify(1, 'SetCursorAnimation', v:true, v:true)
endif
```

**Comment by yatli** [comment]
what option are you referring to?

**Comment by pulcinello** [comment]
I shouldn't call it an 'option'. I just wonder if there's a variable that shows I'm running Fvim.
People may use multiple nvim front-ends, for example, when using Gonvim(It supports font ligatures) he can set font to Fira Code, and when using Fvim he can set other fonts he likes.

**Comment by yatli** [comment]
emm, isn’t that the purpose of g:fvim_running, which is already working?
