### ISSUE TITLE
Failed to run on windows

### ISSUE THREAD

**Issue by wsdjeg** [yatli/fvim#80]
![](https://files.gitter.im/SpaceVim/SpaceVim/nkUz/image.png)

I have opened the link but, too many link in it, and I am not F# user, so I do not know which one I should install, I think more info about requirement should be added in readme.md

**Comment by nree** [comment]
Not sure what is wrong, but if it helps I am on Windows 10. AFAIK you don't need .NET Core or any other requirements except neovim. The files needed are bundled with the release .zip. Does `hostfxr.dll` exist for you in the fvim dir?

Not related to OP @yatli but maybe good idea to inform the user neovim can't be found or state in the README req is neovim ? Maybe some users think that comes bundled. If I remember right, fvim just silently exit if no neovim, can confuse users who don't know.

**Comment by yatli** [comment]
@wsdjeg looks like an API compatibility problem. Are you on older version of Windows?

@nree I just merged the crash report branch a few days ago that gives the tip :)

**Comment by wsdjeg** [comment]
I am using windows os 7.

**Comment by yatli** [comment]
@wsdjeg are you using the specific build for Windows7? Note it's different from `fvim-win-x64.zip`

**Comment by wsdjeg** [comment]
yeah，of cause

--
Best regards,
wsdjeg

**Comment by yatli** [comment]
thank you for the report -- I never get to run it on Win7 so it could be broken from the beginning.
I'll do more tests and get back to you.

**Comment by wsdjeg** [comment]
Thanks, I like this project.

another issue is the startup bin fvim.exe has no icon .

**Comment by yatli** [comment]
@wsdjeg installing this KB update fixed the problem for me:
https://www.microsoft.com/en-us/download/details.aspx?id=26764

**Comment by yatli** [comment]
@nree FYI, the crash dialog:

![image](https://user-images.githubusercontent.com/20684720/66257912-6e867f00-e7d1-11e9-846f-dd8ef28f2e2e.png)

**Comment by wsdjeg** [comment]
ok,  I will  try  again.

**Comment by yatli** [comment]
What's the output of `ver`?

**Comment by wsdjeg** [comment]
It is `Microsoft Windows [版本 6.1.7601]`

**Comment by yatli** [comment]
7601 is SP1 if I remember correctly, if that helps.
Could you please check https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore30 and make sure you have the prereqs? Mostly a KB patch and VCRedist.

**Comment by wsdjeg** [comment]
sorry, I have no time to check it, it is too complex, what I need is a out-of-box version.

**Comment by wsdjeg** [comment]
@yatli Is there any update on this issue? the KB2533623 can not be installed in my os.

**Comment by yatli** [comment]
I have no idea why KB2533623 doesn't work on your side. Is there anything special about the Windows build you're using? What does it say other than "cannot install"?

**Comment by wsdjeg** [comment]
@yatli What I see is just `this patch is not for current os(Chinese)`, and can not debug it. Why this app can not run out of box?

**Comment by yatli** [comment]
Can you provide the verbatim text, maybe in Chinese?

**Comment by wsdjeg** [comment]
ok, sorry for using Chinese.

---

目前使用的系统是：
![image](https://user-images.githubusercontent.com/13142418/75215448-b8492380-57cb-11ea-9d1a-43ca6e9b95c7.png)

ver 命令结果: `Microsoft Windows [版本 6.1.7601]`

从微软官网下载KB2533623

> https://www.microsoft.com/zh-CN/download/details.aspx?id=26764

![image](https://user-images.githubusercontent.com/13142418/75215656-740a5300-57cc-11ea-834f-7920fb87a224.png)

双击安装提示：

![image](https://user-images.githubusercontent.com/13142418/75215683-82586f00-57cc-11ea-84db-59df730100f1.png)

![image](https://user-images.githubusercontent.com/13142418/75215696-884e5000-57cc-11ea-9fdb-56dd36630618.png)

下载最新的 fvim:

> https://github.com/yatli/fvim/releases/download/v0.2-192-gb6a3318/fvim-win7-x64.zip

解压运行：

目前重新测试了，可以正常运行了，感谢开发这个项目。

**Comment by yatli** [comment]
No worry, and thanks for confirming the details!
