### ISSUE TITLE
Different selection colors in fvim

### ISSUE THREAD

**Issue by Kethku** [yatli/fvim#82]
In nvim qt and terminal nvim, selection colors are set by the color scheme.

![image](https://user-images.githubusercontent.com/3323631/65936751-89708200-e3d2-11e9-9671-155fdc5f3d3b.png)

In fvim however they appear to be default or something similar

![image](https://user-images.githubusercontent.com/3323631/65936762-93928080-e3d2-11e9-8739-bfb64a23f826.png)

**Comment by yatli** [comment]
Noted.

Looks like a reverse color calculation error.

**Comment by Kethku** [comment]
Actually I think neovim doesn't use reverse colors to highlight. As you can see the background for the highlight changes based on the thing highlighted. Maybe I'm misunderstanding your comment, but I believe highlighting in vim is more complicated than a reverse color calculation.

**Comment by yatli** [comment]
@Kethku looking at your screenshot I believe what nvim-qt does is to simply swap fg and bg.

Note that in your screenshot the foreground color stays the same (which appears to be the default bg).

This is different from what I understand from the highlight color docs, but if this is the de facto behavior we can implement that.

**Comment by yatli** [comment]
the reverse color calculation is really off.. see 48b42e8014fcc77f9b2ab88da056dc6cd075c5ba

**Comment by yatli** [comment]
hmm, looks like `nvim-gtk` also implement the swapping scheme.

**Comment by yatli** [comment]
pushed out a new release (0.2-132)

**Comment by Kethku** [comment]
I don't think this is the correct fix. It appears that gruvbox itself is manually setting the selection colors. See this issue: https://github.com/morhetz/gruvbox/issues/167

**Comment by Kethku** [comment]
Also note: in a compatible terminal, the colors do the same thing which says to me either the docs or wrong since they don't match the reference implementation or maybe the docs are just confusing

**Comment by Kethku** [comment]
I will try to spend some time to find more information. Thank you for your effort

**Comment by yatli** [comment]
with `let g:gruvbox_invert_selection=0` before setting the colorscheme:

![image](https://user-images.githubusercontent.com/20684720/66257641-66791000-e7ce-11e9-930b-86ba41cd8fbd.png)

check your settings :)

**Comment by Kethku** [comment]
Fair, but given the change between fvim and terminal nvim/nvimqt, doesn't this constitute a bug?

**Comment by yatli** [comment]
the behavior should be identical to other frontends, could you please confirm?

**Comment by Kethku** [comment]
Yes I will. Thanks

Thanks,
Keith
________________________________

**Comment by Kethku** [comment]
Looks like I missed your https://github.com/yatli/fvim/issues/82#issuecomment-538658098 comment! This is working perfectly now. Thank you so much!
