### ISSUE TITLE
CapsLock does not work

### ISSUE THREAD

**Issue by IceNature** [yatli/fvim#85]
CapsLock does not work in fvim. It always inputs lowercase. 
I only can input upper case by hold shift key, but I don't think it is a good idea when I want to input a sequence of upper words.
I use the **v0.2-132-ge81f09a** fvim-win-x64.zip on **Windows 10 x64 1903 18362.418** and **NeoVim 0.4.2** x64 download from NeoVim github release.
It still happened after I deleted my `init.vim` file.
My `ginit.vim`
```viml
if exists('g:fvim_loaded')
    set guifont=Source\ Code\ Pro:h20
    nnoremap <silent> <C-ScrollWheelUp> :set guifont=+<CR>
    nnoremap <silent> <C-ScrollWheelDown> :set guifont=-<CR>
    nnoremap <A-CR> :FVimToggleFullScreen<CR>

    FVimFontAntialias v:true
    FVimFontAutohint v:true
    FVimFontSubpixel v:true
    FVimFontHintLevel 'full'
    FVimFontLcdRender v:true
    FVimFontAutoSnap v:true
    FVimUIPopupMenu v:true
endif
```

**Comment by yatli** [comment]
Thanks for reporting. I bind capslock to esc so I never noticed this :)
Will have to come up with a keycode mapping scheme, to deal with this together with keyboard layout issues altogether -- Avalonia only reports raw keys.

**Comment by natanaeljr** [comment]
Not working on Linux either.
Input keeps lowercase.

**Comment by yatli** [comment]
Upstream issue: https://github.com/AvaloniaUI/Avalonia/issues/2422

**Comment by yatli** [comment]
Good news, Capslock should work now as a side effect of fixing keyboard layouts.
