### ISSUE TITLE
Incorrect font size and position for cmdline completion pop-up menu

### ISSUE THREAD

**Issue by sch0125** [yatli/fvim#91]
Tested on win 10 1903.

* The dialog was not big enough to display items. 

![Capture](https://user-images.githubusercontent.com/840562/68093207-38bae000-fece-11e9-9bb0-02087ddb1f83.PNG)

* The displayed bottom item was over the border and the word starting column seemed 
neither centered nor left aligned.

![2](https://user-images.githubusercontent.com/840562/68093202-3062a500-fece-11e9-9871-8312dab80236.PNG)

**Comment by yatli** [comment]
Didn't know this is already partially working lol
Will look into this, thanks!

**Comment by tssm** [comment]
I just realised the pop-up in the text area can also look weird some times

<img width="1495" alt="Screenshot 2019-11-23 at 16 29 22" src="https://user-images.githubusercontent.com/1188977/69481118-97f57b80-0e0e-11ea-946d-1a8a6c289a5d.png">

**Comment by yatli** [comment]
Let's use this thread to track the popup UI size & positioning problems.

**Comment by yatli** [comment]
@sch0125 @tssm 
PopupUI has been improved.
Feel free to reopen if the problem persists.
