### ISSUE TITLE
windows: cannot start with --ssh arguments from lnk

### ISSUE THREAD

**Issue by codehz** [yatli/fvim#97]
But it works in powershell...
it is really strange..
![image](https://user-images.githubusercontent.com/13158903/69008560-afec7b80-0986-11ea-8487-d0397d2c4b20.png)
(and the window is invisible, I can only see it in taskbar
does it has any log file?

**Comment by yatli** [comment]
It only works when you use a key to log on at the moment :p

**Comment by yatli** [comment]
hmm, should have better error reporting at least.
got bitten today, when the ssh process error out (e.g. host not defined) it just hangs.

**Comment by yatli** [comment]
@codehz could you try the latest head to see if it shows an error dialog.

**Comment by yatli** [comment]
@codehz I have attempted to fix this -- `fvim` was starting too fast and sending a request to open window of size (0, 0) -- which neovim doesn't like.

**Comment by yatli** [comment]
Tested working as of https://github.com/yatli/fvim/commit/9f6430d068a49e96a5952f5016f6e3bbb25f8b4a
